'use strict';
const stages=[['market-research','市场调研','需求与竞争证据'],['product-opportunity','产品机会','机会与验证计划'],['site-and-content','建站','AI / Shopify / WordPress'],['seo-geo','SEO与GEO','搜索优化与证据验收'],['content-operations','内容运营','选题、制作与质量复盘'],['acquisition','主动获客','LinkedIn 主动开发'],['buyer-check','客户背调','匹配程度与风险'],['sales-feedback','销售反馈','跟进与成交结果'],['next-cycle','优化下一轮','反馈驱动新任务']];
let updateInfo=null;let state,token,page='overview';const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const button=(text,action,id='',primary=false)=>`<button type="button" data-action="${action}" data-id="${esc(id)}" class="${primary?'primary':''}">${esc(text)}</button>`;
const label=s=>stages.find(x=>x[0]===s)?.[1]||s;const statuses={'ready':'待执行','needs-review':'待验收','completed':'已验收','blocked':'执行受阻','needs-input':'待补资料'};
function toast(s){$('#toast').textContent=s;$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',4000);}
async function refresh(){try{const r=await fetch('/api/state');if(!r.ok)throw Error('请使用 Node.js 启动工作台服务');state=await r.json();token=state.token;await loadCloudTasks();render();}catch(e){$('#main').innerHTML=`<div class="panel"><h1>项目资料未连接</h1><p>${esc(e.message)}</p><p>请运行：npm start -- --root 客户项目目录 --port 8767</p></div>`;}}
async function save(action,payload){const r=await fetch('/api/save',{method:'POST',headers:{'Content-Type':'application/json','X-Workspace-Token':token},body:JSON.stringify({action,payload,revision:state.revision})});const value=await r.json();if(!r.ok)throw Error(value.error||'保存失败');state={...value,token,projectRoot:state.projectRoot,cloud:state.cloud};await mirrorAfterSave(action,payload);await loadCloudTasks();render();toast('已保存到项目文件');}
/* 页面内按技能规范生成草稿（模式 A）：模型无联网工具，产出须人工核验 */
let aiRun={id:null,busy:false,text:''};
/* 知识底座文件：企业事实为所有阶段共用，另按阶段追加该阶段相关资料，让内容生成 / SEO·GEO 能吃到对应知识 */
const BASE_KB=/organization|brand-profile|products|target-markets|buyer-personas|profile\.md|websites|企业事实|品牌/;
const STAGE_KB={'market-research':['market','competitor','竞品','市场','调研'],'product-opportunity':['product','产品','机会','竞品'],'site-and-content':['site','website','内容','content','建站','页面'],'seo-geo':['seo','geo','keyword','关键词','页面','事实卡','fact','内容'],'content-operations':['content','选题','内容','发布','素材','表现'],'acquisition':['buyer','linkedin','获客','线索','lead','客户'],'buyer-check':['buyer','客户','背调','线索','customer'],'sales-feedback':['feedback','销售','crm','反馈'],'next-cycle':['复盘','反馈','sop','总结']};
function knowledgeBrief(stage){const keys=STAGE_KB[stage]||[];const hit=k=>keys.some(x=>String(k.path).toLowerCase().indexOf(x.toLowerCase())>=0);
 const files=(state.knowledge||[]).filter(k=>BASE_KB.test(k.path)||hit(k));
 return files.map(k=>'【'+k.path+'】\n'+String(k.content||'').slice(0,1800)).join('\n\n').slice(0,12000);}
function stageRecords(stage){return (state.records||[]).filter(r=>r.stage===stage).slice(-5).map(r=>JSON.stringify(r)).join('\n').slice(0,2000);}
async function generateDraft(taskId){const t=(state.tasks||[]).find(x=>x.id===taskId);if(!t)return;const spec=(state.skills||{})[t.stage]||{};
 const box=$('#ai-run');if(!box)return;const err=m=>{const x=$('#dialog-body .error');if(x)x.textContent=m;};
 if(!cloudClient()){err('当前未配置云服务，AI 草稿不可用');return;}
 aiRun={id:taskId,busy:true,text:''};box.innerHTML='';const el=document.createElement('div');el.className='ai-msg assistant';el.textContent='正在按技能规范生成…';box.appendChild(el);
 /* 思考型模型首字可能等待 1-3 分钟，显示计时，避免看起来卡死 */
 const startedAt=Date.now();const wait=setInterval(()=>{if(!aiRun.busy)return clearInterval(wait);if(!aiRun.text)el.textContent='正在按技能规范生成…（已等待 '+Math.round((Date.now()-startedAt)/1000)+' 秒；默认模型带思考过程，首字较慢）';},1000);
 let model;try{model=(await ensureModels())[0];}catch(e){err(e.message||String(e));aiRun.busy=false;clearInterval(wait);return;}
 const sys={role:'system',content:'你是云店+获客工作台的执行助手，严格按给定技能的规范产出中文工作草稿。规则：1) 事实与假设分开标注；2) 不掌握的实时数据（价格、规模、竞品动态）写成「待核验：需补充来源与日期」，禁止编造数字、来源或链接；3) 结构清晰可直接交业务人员补充；4) 结尾列出「缺口与下一步」；5) 知识库给了本阶段相关资料（关键词、可引用事实卡、历史选题与表现、竞品资料）时必须优先引用，并标注来自哪个文件；资料里没有的关键词、排名、数据一律写待核验，不得自行编造。'};
 const user={role:'user',content:['任务：'+t.name,'阶段：'+label(t.stage),'轮次：'+(t.cycleId||'cycle-1'),'输入要求：'+(spec.inputs||t.inputs||''),'执行步骤：'+(spec.instructions||t.instructions||''),'产物要求：'+(spec.outputs||''),'验收标准：'+(spec.acceptance||t.acceptance||''),'企业档案：'+JSON.stringify(state.profile||{}),'企业知识库（企业事实 + 本阶段相关资料）：\n'+knowledgeBrief(t.stage),'本阶段已有记录：\n'+stageRecords(t.stage),'请输出 Markdown 草稿。'].join('\n\n')};
 el.textContent='';
 try{for await(const chunk of cloud.llm.chat.completions.create({model:model.id,stream:true,messages:[sys,user],temperature:1})){const d=chunk.choices&&chunk.choices[0]&&chunk.choices[0].delta&&chunk.choices[0].delta.content;if(d){aiRun.text+=d;el.textContent+=d;box.scrollTop=box.scrollHeight;}}}
 catch(e){err(llmErrorMessage(e));}
 finally{aiRun.busy=false;clearInterval(wait);if(!aiRun.text)el.textContent='';}}
async function runSkillDraft(taskId){const t=(state.tasks||[]).find(x=>x.id===taskId);if(!t)return;const spec=(state.skills||{})[t.stage]||{};
 const lack=!(state.knowledge||[]).length&&!state.profile.company?'<p class="note">提示：当前企业知识库为空，草稿质量会明显下降。先在「企业知识库」补充真实资料，或使用「从知识库填充」完善企业档案。</p>':'';
 modal('AI 草稿 · '+t.name,`<p class="note">按技能 <b>${esc(spec.title||'')}</b>（${esc(spec.id||'')}）的规范生成，输入：${esc(spec.inputs||t.inputs||'未指定')}。模型无联网工具，输出为<b>待核验草稿</b>，关键来源需人工补全或复制任务指令交由 WorkBuddy 联网执行。</p>${lack}<div id="ai-run" class="ai-chat"></div><div class="error" role="alert"></div><div class="actions"><button type="button" data-action="ai-run-save" data-id="${esc(taskId)}" class="primary">保存为产物</button><button type="button" data-action="ai-rerun" data-id="${esc(taskId)}">重新生成</button><button type="button" data-action="ai-run-pdf" data-id="${esc(taskId)}">导出 PDF</button><button type="button" data-action="ai-copy" data-id="${esc(taskId)}">复制全文</button></div>`);
 await generateDraft(taskId);}
async function autofillProfile(){const fm=document.querySelector('#dialog-body form');if(!fm)return;
 if(!cloudClient()){toast('当前未配置云服务，无法自动提取');return;}
 if(!(state.knowledge||[]).length){toast('企业知识库为空，请先添加真实资料再填充');return;}
 toast('正在从知识库提取企业信息…');
 const sys={role:'system',content:'你是企业信息抽取助手。只依据给定资料提取，禁止推测、补充或编造；资料中没有的字段返回空字符串。只输出 JSON，键与要求：company=企业主体与品牌名（中英文，不超过 40 字）；products=产品与服务（不超过 200 字）；markets=目标市场；persona=买家画像；goal=获客目标；brand=品牌与业务约束；source=资料来源与文件路径。不要写入联系人姓名、手机号、二维码等没有对应字段的信息。'};
 const user={role:'user',content:'资料：\n'+knowledgeBrief()+'\n\n已有档案（可补全但不要覆盖已有值）：'+JSON.stringify(state.profile||{})};
 let busy=true,t0=Date.now();const timer=setInterval(()=>{if(!busy){clearInterval(timer);return;}toast('正在从知识库提取企业信息…（已等待 '+Math.round((Date.now()-t0)/1000)+' 秒）');},5000);
 try{const model=(await ensureModels())[0];let text='';
  for await(const chunk of cloud.llm.chat.completions.create({model:model.id,stream:true,messages:[sys,user],temperature:0})){const d=chunk.choices&&chunk.choices[0]&&chunk.choices[0].delta&&chunk.choices[0].delta.content;if(d)text+=d;}
  busy=false;clearInterval(timer);
  const data=JSON.parse(text.replace(/^```json/i,'').replace(/```$/,'').trim());
  let filled=0;for(const k of ['company','products','markets','persona','goal','brand','source']){const el=fm.querySelector('[name='+k+']');if(el&&!el.value&&typeof data[k]==='string'&&data[k]){el.value=data[k];filled++;}}
  toast(filled?'已从知识库填充 '+filled+' 项，请核对后再保存':'知识库未提取到可填充内容，请手动补充');
 }catch(e){busy=false;clearInterval(timer);toast('提取失败：'+(e.message||e));}}
/* 产物 / 草稿导出 PDF：新开窗口打印，内容留在浏览器侧，不上传 */
function printPdf(title,content){const w=window.open('','_blank');if(!w){toast('请允许弹出窗口后再导出 PDF');return;}w.document.write(`<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><title>${esc(title)}</title><style>body{font-family:"Microsoft YaHei",sans-serif;line-height:1.9;padding:36px;color:#24344b}h1{font-size:20px;margin:0 0 8px}.meta{font-size:12px;color:#7a8aa0;margin:0 0 18px}pre{white-space:pre-wrap;font-family:inherit;font-size:13px}</style></head><body><h1>${esc(title)}</h1><p class="meta">云店+获客工作台 · ${esc(state.profile.company||'')} · ${esc(new Date().toLocaleString('zh-CN'))}</p><pre>${esc(content)}</pre></body></html>`);w.document.close();w.focus();setTimeout(()=>w.print(),400);}
function exportPdf(id){const content=cloudArtifacts[id]||'';const t=(state.tasks||[]).find(x=>x.id===id);printPdf(t?t.name:'工作产物',content);}

/* ===== WorkBuddy 云服务（LLM + Database，配置由服务端 /api/state 下发）===== */
let cloud=null,cloudModelList=null,aiChat={history:[],conversationId:String(Date.now()),busy:false};
function cloudReady(){return !!(state&&state.cloud&&window.WorkBuddyCloud&&WorkBuddyCloud.createWorkBuddyCloud);}
function cloudClient(){if(cloud)return cloud;if(!cloudReady())return null;cloud=WorkBuddyCloud.createWorkBuddyCloud({endpoint:state.cloud.endpoint,publishableKey:state.cloud.publishableKey});return cloud;}
function llmErrorMessage(e){const code=e&&e.error&&e.error.code||'';if(code.indexOf('auth_')===0)return '云服务鉴权失败（本地访问或非线上域名来源时不支持，请通过工作台线上链接使用）';if(code.indexOf('quota_')===0)return '模型额度不足或触发限流，请稍后再试';if(code.indexOf('request_')===0)return '请求参数错误：'+((e&&e.error&&e.error.message)||code);if(code.indexOf('gateway_')===0||code.indexOf('model_')===0)return '模型服务暂时不可用，请稍后重试';return (e&&e.message)||'调用失败';}
async function ensureModels(){if(cloudModelList&&cloudModelList.length)return cloudModelList;const c=cloudClient();if(!c)throw Error('云服务未配置或 SDK 未加载');const list=await c.llm.models.list();cloudModelList=(list||[]).filter(m=>m.disabled!==true);if(!cloudModelList.length)throw Error('当前云服务没有可用模型');return cloudModelList;}
function renderAiChat(){const box=$('#ai-chat');if(!box)return;box.innerHTML=aiChat.history.length?aiChat.history.map(m=>`<div class="ai-msg ${m.role}">${esc(m.content)}</div>`).join(''):'<div class="empty">向 AI 增长助手提问，例如：根据当前业务阶段，建议下一步获客动作。</div>';box.scrollTop=box.scrollHeight;}
function aiPanel(){if(!cloudClient()){modal('AI 增长助手','<div class="empty">当前环境未配置 WorkBuddy 云服务。<br>在 WorkBuddy 中为应用开通云服务并写入 cloud-config.json 后，此处自动启用。</div>');return;}aiChat.conversationId=(crypto.randomUUID?crypto.randomUUID():String(Date.now()));aiChat.history=[];modal('AI 增长助手','<p class="note">基于 WorkBuddy 云服务大模型能力；回答仅供参考，关键事实需人工核实。</p><div id="ai-chat" class="ai-chat"></div><form id="ai-form"><textarea name="q" placeholder="输入你的获客问题…" required></textarea><div class="error" role="alert"></div><div class="actions"><button type="submit" class="primary">发送</button><button type="button" data-action="ai-new">新对话</button></div></form>');renderAiChat();$('#dialog-body form#ai-form').onsubmit=async e=>{e.preventDefault();const q=e.target.q.value.trim();if(!q||aiChat.busy)return;e.target.q.value='';await aiSend(q);};}
async function aiSend(q){const err=m=>{const x=$('#dialog-body .error');if(x)x.textContent=m;};if(!cloudClient()){err('云服务未配置或 SDK 未加载，请检查网络后刷新');return;}
 let model;try{model=(await ensureModels())[0];}catch(e){err(e.message||String(e));return;}
 aiChat.busy=true;aiChat.history.push({role:'user',content:q});renderAiChat();const box=$('#ai-chat');const ans=document.createElement('div');ans.className='ai-msg assistant';ans.textContent='思考中…';box.appendChild(ans);box.scrollTop=box.scrollHeight;
 const sys={role:'system',content:'你是云店+获客工作台的 AI 增长助手。企业：'+(state.profile.company||'未填写')+'；获客目标：'+(state.profile.goal||'未填写')+'。聚焦跨境 B2B 获客实战，回答务实简洁；事实与假设分开，不确定就明确说明，不要编造。'};
 let answer='';try{for await(const chunk of cloud.llm.chat.completions.create({model:model.id,stream:true,conversationId:aiChat.conversationId,messages:[sys,...aiChat.history.slice(-10)],temperature:1})){const d=chunk.choices&&chunk.choices[0]&&chunk.choices[0].delta&&chunk.choices[0].delta.content;if(d){if(!answer)ans.textContent='';answer+=d;ans.textContent+=d;box.scrollTop=box.scrollHeight;}}}
 catch(e){err(llmErrorMessage(e));if(!answer){ans.remove();aiChat.history.pop();renderAiChat();}}
 finally{aiChat.busy=false;}
 if(answer)aiChat.history.push({role:'assistant',content:answer});}
async function loadCloudFeedback(){const box=$('#cloud-feedback');if(!box)return;if(!cloudClient()){box.innerHTML='<div class="empty">当前环境未配置 WorkBuddy 云服务；反馈仅保存在本地项目文件中。</div>';return;}box.textContent='正在读取云端反馈…';try{const {data,error}=await cloud.database.from('sales_feedback').select('id,lead_id,result,source,reason,next,cycle_id,created_at').order('created_at',{ascending:false}).limit(50);if(error)throw error;box.innerHTML=(data&&data.length)?data.map(f=>`<div class="row"><div><h3>${esc(f.lead_id)} · ${esc(f.result)}</h3><p>${esc(f.source||'')} / ${esc(f.reason||'')}</p><p>下一步：${esc(f.next||'待定')} · ${esc(new Date(f.created_at).toLocaleString())}</p></div></div>`).join(''):'<div class="empty">云端暂无反馈记录。</div>';}catch(e){box.innerHTML='<div class="empty">云端反馈读取失败：'+esc(e.message||e)+'</div>';}}
async function syncFeedbackToCloud(payload){try{const c=cloudClient();if(!c)return;const {error}=await c.database.from('sales_feedback').insert({lead_id:String(payload.leadId||'').slice(0,200),result:String(payload.result||'').slice(0,2000),source:String(payload.source||'').slice(0,1000),reason:String(payload.reason||'').slice(0,4000),next:String(payload.next||'').slice(0,4000),cycle_id:String(payload.cycleId||'').slice(0,100)});if(error)throw error;toast('销售反馈已同步云端');if(page==='sales-feedback')loadCloudFeedback();}catch(e){toast('已保存到本地；云端同步失败：'+(e.message||e));}}

/* 任务与产物云端持久化：本地文件与云库互为备份；云库是 WorkBuddy 回写真实结果的通道 */
let cloudArtifacts={},lastLocalSaveAt='';
const taskRow=(t)=>({id:String(t.id),stage:String(t.stage||''),name:String(t.name||''),status:String(t.status||'ready'),cycle_id:t.cycleId||null,instructions:t.instructions||null,inputs:t.inputs||null,acceptance:t.acceptance||null,skill_id:t.skillId||null,skill_path:t.skillPath||null,artifact:t.artifact||null,review:t.review||null,reviewed_hash:t.reviewedHash||null,created_at:t.createdAt||new Date().toISOString(),finished_at:t.finishedAt||null,updated_at:new Date().toISOString()});
async function loadCloudTasks(){const c=cloudClient();if(!c)return false;try{
  const {data,error}=await c.database.from('workbench_tasks').select('*').order('created_at',{ascending:false}).limit(200);
  if(error)throw error;
  const byId=Object.fromEntries((state.tasks||[]).map(t=>[String(t.id),t]));
  for(const r of data||[]){
    const mapped={id:r.id,stage:r.stage,name:r.name,status:r.status,cycleId:r.cycle_id,instructions:r.instructions,inputs:r.inputs,acceptance:r.acceptance,skillId:r.skill_id,skillPath:r.skill_path,artifact:r.artifact||null,review:r.review||null,reviewedHash:r.reviewed_hash||null,createdAt:r.created_at,finishedAt:r.finished_at,updatedAt:r.updated_at,cloud:true};
    const local=byId[r.id];
    if(!local) state.tasks.push(mapped);
    else if(String(r.updated_at||r.created_at||'')>String(local.updatedAt||local.createdAt||'')) Object.assign(local,mapped);
  }
  const arts=await c.database.from('workbench_artifacts').select('task_id,content').limit(200);
  if(!arts.error) for(const a of arts.data||[]) cloudArtifacts[a.task_id]=a.content;
  const prof=await c.database.from('workbench_profile').select('*').eq('id','default').maybeSingle();
  if(!prof.error&&prof.data){const d=prof.data;const mapped={company:d.company||'',products:d.products||'',markets:d.markets||'',persona:d.persona||'',goal:d.goal||'',brand:d.brand||'',source:d.source||'',projectRef:d.project_ref||'',spaceRef:d.space_ref||''};
    if(!state.profile||!state.profile.company||String(d.updated_at||'')>lastLocalSaveAt) state.profile=mapped;}
  return true;
}catch(e){return false;}}
async function mirrorTaskRow(t){const c=cloudClient();if(!c||!t)return;const {error}=await c.database.from('workbench_tasks').upsert(taskRow(t));if(error)throw error;}
async function mirrorAfterSave(action,payload){const c=cloudClient();if(!c)return;try{lastLocalSaveAt=new Date().toISOString();
  if(action==='profile'){const p=state.profile||{};const {error}=await c.database.from('workbench_profile').upsert({id:'default',company:p.company||null,products:p.products||null,markets:p.markets||null,persona:p.persona||null,goal:p.goal||null,brand:p.brand||null,source:p.source||null,project_ref:p.projectRef||null,space_ref:p.spaceRef||null,updated_at:new Date().toISOString()});if(error)throw error;}
  else if(action==='task'){const t=[...(state.tasks||[])].reverse().find(x=>x.name===payload.name&&(x.stage===payload.stage||x.stage===undefined));if(t)await mirrorTaskRow(t);}
  else if(action==='artifact'){const {error}=await c.database.from('workbench_artifacts').upsert({task_id:String(payload.id),content:String(payload.content||''),updated_at:new Date().toISOString()});if(error)throw error;const t=(state.tasks||[]).find(x=>x.id===payload.id);if(t)await mirrorTaskRow(t);}
  else if(action==='review'){const t=(state.tasks||[]).find(x=>x.id===payload.id);if(t)await mirrorTaskRow(t);}
}catch(e){toast('已保存到本地；云端同步失败：'+(e.message||e));}}
async function viewArtifact(id){const t=(state.tasks||[]).find(x=>x.id===id);let content=cloudArtifacts[id]||'';
  if(!content){try{const r=await fetch('/api/artifact/'+encodeURIComponent(id)+'.md');if(r.ok)content=await r.text();}catch(e){}}
  if(!content&&cloudClient()){try{const {data}=await cloud.database.from('workbench_artifacts').select('content').eq('task_id',id).maybeSingle();if(data&&data.content){content=data.content;cloudArtifacts[id]=content;}}catch(e){}}
  modal('工作产物'+(t?'：'+t.name:''),content?`<div class="knowledge">${esc(content)}</div><div class="actions">${button('导出 PDF','pdf',id,true)}</div>`:'<div class="empty">该任务还没有产物内容。</div>');}
function heading(title,desc,actions=''){return `<div class="heading"><div><div class="eyebrow">YUNDIAN+ / AI GROWTH</div><h1>${title}</h1><p>${desc}</p></div><div class="actions">${actions}</div></div>`;}
function tasks(rows){return rows.length?rows.map(t=>`<div class="row"><div><h3>${esc(t.name)}</h3><p>${esc(label(t.stage))} · ${esc(t.cycleId)}</p></div><div class="actions"><span class="pill ${t.status==='completed'?'done':''}">${esc(statuses[t.status]||t.status)}</span>${button('查看任务','task',t.id)}</div></div>`).join(''):'<div class="empty">还没有任务<br>根据当前业务阶段，创建第一项获客工作。</div>';}
const recordFields={
'market-research':[['market','国家/细分市场'],['buyer','目标买家'],['hypothesis','需求结论 / 待验证假设']],
'product-opportunity':[['product','产品/规格'],['market','国家'],['buyer','应用/买家'],['hypothesis','机会假设'],['constraints','成本/认证/供货缺口'],['opportunityId','稳定机会ID']],
'site-and-content':[['platform','AI / Shopify / WordPress'],['url','站点/预览URL'],['constraints','部署权限与验收缺口']],
'content-operations':[['product','产品/主题'],['buyer','目标读者'],['platform','渠道/格式'],['url','实际内容文件/发布URL'],['status','草稿/已发布/待验证']],
'acquisition':[['leadId','稳定线索ID'],['url','LinkedIn企业/联系人URL'],['buyer','采购角色'],['opportunityId','关联机会ID'],['next','开发草稿/下一步']],
'buyer-check':[['leadId','稳定线索ID'],['url','主体官网/职业资料'],['buyer','主体/采购关系'],['result','核验/匹配/意向结论'],['next','待核问题与跟进']],
'sales-feedback':[['leadId','稳定线索ID'],['result','实际联系/报价/成交结果'],['next','下一轮建议']],
'next-cycle':[['hypothesis','改进假设'],['result','实际销售反馈依据'],['next','验证任务与停止标准']]
};
function businessPanel(){if(page==='seo-geo')return `<section class="panel"><div class="heading"><h2>SEO / GEO 验收台账</h2>${button('创建完整验收台账','audit-new','',true)}</div>${(state.audits||[]).map(a=>`<h3>${esc(a.platform)} · ${a.items.length} 项</h3>${a.items.map(i=>`<div class="row"><div><strong>${esc(i.id)} ${esc(i.title)}</strong><p>${esc(i.level)} · ${esc(i.result)} · ${esc(i.evidence?.join('；')||'无证据')}</p></div>${button('填写检查结果','audit-item',a.id+':'+i.id)}</div>`).join('')}`).join('')||'<div class="empty">先选择Shopify或WordPress，生成全部待验证检查项。</div>'}</section>`;return `<section class="panel"><div class="heading"><h2>阶段资料与实际结果</h2>${button('添加业务记录','record','',true)}</div>${(state.records||[]).filter(r=>r.stage===page).map(r=>`<div class="row"><div><h3>${esc(r.name)}</h3><p>${Object.entries(r).filter(([k,v])=>!['id','stage','name','createdAt'].includes(k)&&v).map(([k,v])=>esc(k)+': '+esc(v)).join('<br>')}</p></div>${button('据此创建任务','record-task',r.id)}</div>`).join('')||'<div class="empty">保存真实输入、来源和结果，再交给对应技能处理。</div>'}</section>`;}
function render(){const nav=[['overview','增长总览'],['knowledge','企业知识库'],...stages.map(x=>[x[0],x[1]]),['artifacts','工作产物'],['settings','项目与设置']];$('#sidebar').innerHTML=`<div class="brand"><img src="${esc(state.settings?.avatar||'brand.jpg')}" alt="项目头像"><div><strong>云店+</strong><small>AI GROWTH</small></div></div><div class="project-label"><span class="muted">当前项目</span><strong>${esc(state.profile.company||'待创建企业知识库')}</strong><span class="muted">WorkBuddy 获客工作台</span></div><nav>${nav.map(([id,name],i)=>`<button data-action="nav" data-id="${id}" class="${page===id?'active':''}"><small>${i===0?'⌂':i===1?'▤':i<9?String(i-1).padStart(2,'0'):'·'}</small>${name}</button>`).join('')}</nav><footer>知识驱动 · 客户自主定制<br>真实文件保存 / ${esc(state.version)}</footer>`;
const setup=!state.profile.company?`<section class="panel setup"><div><h2>先建立企业知识库</h2><p>关联项目 → 添加企业资料 → 明确获客目标 → 启动第一项工作</p></div>${button('创建知识库','profile','',true)}</section>`:'';
let html='';
if(page==='overview'){html=heading('今天推进哪一步获客工作？',state.profile.goal||'先整理企业知识，再让 WorkBuddy 按业务阶段执行。',(state.cloud?button('AI 增长助手','ai'):'')+button('创建获客任务','new-task','',true))+setup+`<div class="path">${stages.map(([id,name,desc],i)=>`<button class="stage" data-action="nav" data-id="${id}"><span>${String(i+1).padStart(2,'0')}</span><strong>${name}</strong><small>${desc}</small></button>`).join('')}</div><div class="columns"><section class="panel"><h2>我的获客任务</h2>${tasks(state.tasks.filter(t=>t.status!=='completed'))}</section><section class="panel"><h2>共同的知识底座</h2><p>${state.profile.company?'企业资料已保存。每项任务使用同一组企业事实与来源。':'尚未填写企业、产品和目标市场。'}</p>${button('整理企业资料','profile')}<div class="row"><span>WorkBuddy 原生资料关联</span><span class="pill">待宿主验证</span></div><p class="note">优先使用本地企业知识，在 WorkBuddy 执行任务；ima、乐享及云端空间按需授权，未关联不阻塞本地工作。</p></section></div>`;}
else if(page==='knowledge'){html=heading('企业知识库','七步获客工作共同使用的事实与来源。',button('添加知识资料','knowledge','',true)+button('编辑企业资料','profile')+button('知识整理指令','knowledge-skill'))+setup+state.knowledge.map(k=>`<section class="panel"><h2>${esc(k.path)}</h2><div class="knowledge">${esc(k.content)}</div></section>`).join('');}
else if(page==='settings'){html=heading('项目与设置','使用当前客户项目文件，保留 WorkBuddy 原生执行入口。')+`<section class="panel"><h2>项目头像</h2><img src="${esc(state.settings?.avatar||'brand.jpg')}" alt="当前头像" style="width:72px;height:72px;object-fit:cover;border-radius:16px"><p><label>上传头像（PNG/JPEG/WebP，最大256KB）<input id="avatar-file" type="file" accept="image/png,image/jpeg,image/webp"></label></p>${button('恢复默认头像','avatar-reset')}<p class="note">保存在客户本地项目，不上传到版本检查服务。</p></section><section class="panel"><h2>版本与更新</h2><p>当前版本：${esc(state.version)}</p><p>${updateInfo?updateInfo.error?esc(updateInfo.error):updateInfo.available?'发现新版本：'+esc(updateInfo.latest):'已检查发布版本：'+esc(updateInfo.latest)+'，无需更新':'尚未检查'}</p>${button('检查新版本','check-update')}${updateInfo?.available?button('WorkBuddy 更新部署指令','update-guide','',true):''}<p class="note">在 WorkBuddy 更新；先备份并合并本地定制，冲突不强制覆盖。${esc(updateInfo?.notes||'')}</p></section>`+`<section class="panel"><h2>功能技能</h2>${button('安装项目技能','install-skills','',true)}<p class="note">安装到当前项目 .codebuddy/skills/，同名不同内容不覆盖。文件安装不等于宿主已加载。</p>${Object.values(state.skills).map(x=>`<div class="row"><span>${esc(x.title)}</span><span class="pill">${x.status==='installed'?'项目文件已安装':x.status==='different'?'客户版本不同':'待安装'}</span></div>`).join('')}<h2>实际文件目录</h2><div class="knowledge">${esc(state.projectRoot)}\ngrowth-workspace/</div><p class="note">启动时用 --root 选择客户项目；不同客户使用独立目录。</p><h2>WorkBuddy 项目 / 空间</h2><p>项目：${esc(state.profile.projectRef||'未填写')}<br>空间：${esc(state.profile.spaceRef||'未填写')}<br>关联状态：待宿主验证</p>${button('填写关联资料','profile')}<p class="note">在 WorkBuddy 项目中启用 yundian-growth-workbench 技能，上传知识文件到项目资料库。平台当前不自动创建云端空间，不保存供应商密钥。广告仅只读分析。</p></section>`;}
else if(page==='artifacts'){html=heading('工作产物','已保存的实际文件，验收与任务完成分别记录。')+`<section class="panel">${state.tasks.filter(t=>t.artifact||cloudArtifacts[t.id]).map(t=>`<div class="row"><div><h3>${esc(t.name)}</h3><p>${esc(t.artifact||'云端产物')}${t.cloud?' · 云端同步':''}</p></div><div class="actions">${button('查看','view-artifact',t.id,true)}${button('导出 PDF','pdf',t.id)}${t.artifact?`<a target="_blank" rel="noopener" href="/api/artifact/${encodeURIComponent(t.id)}.md">原始文件 ↗</a>`:''}</div></div>`).join('')||'<div class="empty">暂无产物。完成 WorkBuddy 工作后，保存实际结果。</div>'}</section>`;}
else{html=heading(label(page),stages.find(x=>x[0]===page)?.[2]||'',button('定制阶段任务','new-task',page,true))+setup;if(page==='site-and-content'||page==='acquisition'||page==='content-operations')html+=`<div class="service-links">${(page==='site-and-content'?['AI建站','Shopify独立站','WordPress定制建站']:page==='content-operations'?['内容选题','内容制作','内容发布计划','内容效果复盘']:['LinkedIn 买家筛选','LinkedIn 联系人核验','LinkedIn 开发信草稿','LinkedIn 跟进计划']).map(s=>button(s,'service',s)).join('')}</div>`;html+=businessPanel();html+=`<section class="panel"><h2>阶段工作</h2><p class="note">技能：${esc(state.skills[page]?.id||'')} · ${state.skills[page]?.status==='installed'?'项目文件已安装（宿主加载待验证）':'待安装或版本不同'}</p>${tasks(state.tasks.filter(t=>t.stage===page))}</section>`;if(page==='sales-feedback')html+=`<section class="panel"><div class="heading"><h2>真实销售反馈</h2>${button('记录反馈','feedback','',true)}</div>${state.feedback.map(f=>`<div class="row"><div><h3>${esc(f.leadId)} · ${esc(f.result)}</h3><p>${esc(f.source)} / ${esc(f.reason)}</p><p>下一步：${esc(f.next||'待定')}</p></div></div>`).join('')||'<div class="empty">暂无实际反馈。记录联系、报价、成交或拒绝原因。</div>'}</section>`;
if(page==='sales-feedback')html+=`<section class="panel"><div class="heading"><h2>云端同步反馈</h2><span class="pill">WorkBuddy 云服务</span></div><p class="note">反馈保存到本地文件的同时写入云端数据库，跨设备、实例重建后不丢失。</p><div id="cloud-feedback">正在读取云端反馈…</div></section>`;if(page==='next-cycle')html+=`<section class="panel"><h2>下一轮优化依据</h2><p>${state.feedback.length?`已有 ${state.feedback.length} 条客户反馈，可关联渠道与线索调整下一轮任务。`:'等待实际线索及销售反馈。可以建立验证假设，不以预测冒充获客结果。'}</p></section>`;}
$('#main').innerHTML=html+'<p class="footer-note">市场调研 → 产品机会 → 建站 / SEO与GEO / 内容运营 → 主动获客 → 客户背调 → 销售反馈 → 优化下一轮</p>';if(page==='sales-feedback')loadCloudFeedback();}
function modal(title,body){$('#dialog-title').textContent=title;$('#dialog-body').innerHTML=body;$('#dialog').showModal();}
function field(name,title,value='',area=false){return `<label>${esc(title)}${area?`<textarea name="${name}">${esc(value)}</textarea>`:`<input name="${name}" value="${esc(value)}">`}</label>`;}
function form(title,body,action,extra={},onSaved){modal(title,`<form>${body}<div class="error" role="alert"></div><div class="actions"><button type="submit" class="primary">保存</button></div></form>`);$('#dialog-body form').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button[type=submit]');b.disabled=true;try{const payload={...Object.fromEntries(new FormData(e.target)),...extra};await save(action,payload);$('#dialog').close();if(onSaved)onSaved(payload);}catch(err){e.target.querySelector('.error').textContent=err.message;}finally{b.disabled=false;}};}
function prompt(t){return `必须读取并使用对应功能技能：${t.skillId||state.skills[t.stage].id}\n技能文件：${t.skillPath||state.skills[t.stage].installedPath}\n若未安装，先在工作台项目与设置安装技能。\n使用 yundian-growth-workbench 主技能，在当前 WorkBuddy 客户项目执行真实任务。\n项目目录：${state.projectRoot}\n企业：${state.profile.company}\n获客目标：${state.profile.goal}\n阶段：${label(t.stage)}\n轮次：${t.cycleId}\n任务：${t.name}\n输入/上游产物：${t.inputs||'先读取 knowledge 目录，缺失则补资料'}\n步骤/工具：${t.instructions||'按客户目标定制实际工作流'}\n验收：${t.acceptance||'产物可读、来源可追溯；未知事实标记待确认'}\n将实际产物写入 growth-workspace/artifacts/${t.id}.md，并更新任务记录。执行失败不得模拟成功。广告只读；外部动作按实际授权。默认读取本地知识；使用外部来源时核验宿主授权和出处。\n完成实际工作后运行：node \"${state.projectRoot}/.codebuddy/skills/yundian-growth-workbench/scripts/submit_result.mjs\" --root \"${state.projectRoot}\" --task ${t.id} --file \"${state.projectRoot}/growth-workspace/artifacts/${t.id}.md\"。受阻时用 --status blocked --reason 说明。然后刷新工作台并记录客户验收。`;}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const {action,id}=b.dataset;
if(action==='avatar-reset')save('avatar',{avatar:''}).catch(e=>toast(e.message));
if(action==='check-update')checkUpdate();
if(action==='update-guide')modal('WorkBuddy 更新部署',`<div class="prompt">${esc(updatePrompt())}</div><p class="note">交给当前项目 WorkBuddy 执行；此页面不会直接更新代码。</p>`);
if(action==='install-skills'){save('install-skills',{}).catch(e=>toast(e.message));}
if(action==='nav'){page=id;render();$('#sidebar').classList.remove('open');if(page==='settings'&&!updateInfo)checkUpdate();}
if(action==='profile'){const p=state.profile;form('企业知识库与项目资料',`<div class="form-grid">${[['company','企业名称'],['products','产品 / 服务'],['markets','目标市场'],['persona','买家画像'],['goal','获客目标'],['brand','品牌与业务约束'],['source','资料来源 / 文件路径'],['projectRef','WorkBuddy 项目名称 / 链接'],['spaceRef','关联空间名称 / 链接']].map(([k,v])=>field(k,v,p[k]||'',k==='goal'||k==='source')).join('')}</div><div class="actions">${state.cloud?button('从知识库填充','profile-autofill'):''}</div><p class="note">「从知识库填充」只读取项目 knowledge 目录下已保存的真实资料，由云端模型提取，资料中没有的字段留空；只填充未填写项，保存前请逐项核对。填写名称/链接不会自动关联云端空间；需在 WorkBuddy 中完成并验证。</p>`,'profile');}
if(action==='record'){form('保存阶段业务记录',field('name','记录名称')+field('source','真实来源URL / 文件 / 客户反馈')+field('cycleId','轮次ID','cycle-1')+(recordFields[page]||[]).map(([k,n])=>field(k,n,'',true)).join(''),'record',{stage:page});}
if(action==='record-task'){const r=state.records.find(x=>x.id===id);form('从业务记录创建技能任务',field('name','任务名称',r.name)+field('inputs','实际输入与上游资料',JSON.stringify(r,null,2),true)+field('instructions','具体工作步骤','读取对应技能，核对输入、证据与缺口，保存真实报告。',true)+field('acceptance','验收标准','来源可追溯，事实与假设分开，缺项明确，实际产物可读回。',true),'task',{stage:r.stage,cycleId:r.cycleId||'cycle-1'});}
if(action==='audit-new'){form('创建全量验收台账','<label>站点平台<select name="platform"><option value="shopify">Shopify · 38项</option><option value="wordpress">WordPress · 26项</option></select></label>','audit-create');}
if(action==='audit-item'){const [auditId,itemId]=id.split(':');const a=state.audits.find(x=>x.id===auditId);const i=a.items.find(x=>x.id===itemId);form(itemId+' '+i.title,`<p class="note">${esc(i.requirement)}</p><label>结果<select name="result">${['待验证','通过','未通过','不适用'].map(x=>`<option ${x===i.result?'selected':''}>${x}</option>`).join('')}</select></label>`+field('evidence','实际证据URL / 文件 / 测试记录',i.evidence?.join('；')||'',true)+field('reason','原因 / 不适用理由',i.reason||'',true)+field('owner','责任人',i.owner||'')+field('remediation','整改动作',i.remediation||'',true)+field('recheckDate','复查日期',i.recheckDate||''),'audit-item',{auditId,itemId});}
if(action==='new-task'||action==='service'){const stage=stages.some(x=>x[0]===id)?id:stages.some(x=>x[0]===page)?page:'market-research';form('定制获客任务',`${field('name','任务名称',action==='service'?id:'')}<label>获客阶段<select name="stage">${stages.map(([k,n])=>`<option value="${k}" ${k===stage?'selected':''}>${n}</option>`).join('')}</select></label>${field('cycleId','轮次标识','cycle-1')}${field('inputs','输入来源 / 上游产物',state.skills[stage]?.inputs?'待提供：'+state.skills[stage].inputs:'',true)}${field('instructions','工作步骤 / 所需工具',state.skills[stage]?.instructions||'',true)}${field('acceptance','验收规则',state.skills[stage]?.acceptance||'',true)}`,'task');const selector=document.querySelector('dialog select[name=stage]');selector.dataset.defaultStage=stage;selector.addEventListener('change',()=>{const before=state.skills[selector.dataset.defaultStage],after=state.skills[selector.value];for(const [name,key] of [['inputs','inputs'],['instructions','instructions'],['acceptance','acceptance']]){const control=document.querySelector('dialog [name='+name+']');const previous=name==='inputs'?'待提供：'+before.inputs:before[key];if(control.value===previous)control.value=name==='inputs'?'待提供：'+after.inputs:after[key];}selector.dataset.defaultStage=selector.value;});}
if(action==='knowledge-skill'){const instruction=`读取并调用 ${state.skills.knowledge.installedPath}，使用 yundian-growth-knowledge 技能。项目目录：${state.projectRoot}。整理 growth-workspace/knowledge/ 中的真实企业资料、来源、审核状态与缺口，保留原资料；优先使用当前本地知识库；客户需要外部资料时再关联ima或腾讯乐享并核验授权。没有工具时说明缺口，不伪造关联成功。实际更新知识文件和索引，然后刷新工作台。`;modal('企业知识库技能',`<div class="prompt">${esc(instruction)}</div><p class="note">在 WorkBuddy 当前项目执行。技能文件状态：${state.skills.knowledge.status==='installed'?'已安装，宿主加载待验证':'待安装或版本不同'}。</p>`);}
if(action==='knowledge')form('添加真实知识资料',field('title','资料标题')+field('content','实际资料内容','',true)+field('source','来源 URL / 文件路径'),'knowledge');
if(action==='feedback')form('记录真实销售反馈',`${field('leadId','稳定线索标识')}${field('source','获客渠道 / 上游产物')}${field('cycleId','轮次标识','cycle-1')}${field('result','实际联系 / 报价 / 成交结果')}${field('reason','有效或无效原因','',true)}${field('next','下一轮改进建议','',true)}`,'feedback',{},syncFeedbackToCloud);
if(action==='task'){const t=state.tasks.find(t=>t.id===id);modal(t.name,`<p>${esc(label(t.stage))} · ${esc(statuses[t.status])}${t.cloud?' · 云端同步':''}</p><div class="prompt">${esc(prompt(t))}</div><p class="note">复制指令到 WorkBuddy 当前项目执行；这里不会模拟调用模型。WorkBuddy 执行后产物会回写到云端，此处刷新即可看到。</p><div class="actions">${button('复制 WorkBuddy 指令','copy',id,true)}${state.cloud?button('AI 生成草稿','ai-run',id):''}${button('保存实际产物','artifact',id)}${(t.artifact||cloudArtifacts[t.id])?button('查看产物','view-artifact',id):''}${t.artifact?button('记录验收','review',id):''}</div>`);}
if(action==='view-artifact')viewArtifact(id);
if(action==='pdf')exportPdf(id);
if(action==='ai-run')runSkillDraft(id);
if(action==='ai-rerun')generateDraft(id);
if(action==='ai-run-save'){if(!aiRun.text.trim()){toast('还没有生成内容');return;}save('artifact',{id,content:aiRun.text}).then(()=>{$('#dialog').close();toast('草稿已保存为产物，状态待验收');}).catch(err=>toast(err.message));}
if(action==='ai-run-pdf'){if(!aiRun.text.trim()){toast('还没有生成内容');return;}const t=state.tasks.find(x=>x.id===id);printPdf((t?t.name:'工作产物')+' · AI 草稿（待核验）',aiRun.text);}
if(action==='ai-copy'){navigator.clipboard.writeText(aiRun.text||'').then(()=>toast('已复制草稿全文')).catch(()=>toast('请手动选中复制'));}
if(action==='profile-autofill')autofillProfile();
if(action==='ai')aiPanel();
if(action==='ai-new'){aiChat.conversationId=(crypto.randomUUID?crypto.randomUUID():String(Date.now()));aiChat.history=[];const f=$('#dialog-body .error');if(f)f.textContent='';renderAiChat();}
if(action==='copy'){navigator.clipboard.writeText(prompt(state.tasks.find(t=>t.id===id))).then(()=>toast('指令已复制，请在 WorkBuddy 当前项目执行')).catch(()=>toast('请手动选中并复制任务指令'));}
if(action==='artifact'){form('保存实际工作产物',field('content','产物内容（含来源与结果）','',true),'artifact',{id});}
if(action==='review'){form('记录客户验收',field('review','实际验收依据','',true),'review',{id});}
});$('#close').onclick=()=>$('#dialog').close();$('#menu').onclick=()=>$('#sidebar').classList.toggle('open');$('#refresh').onclick=refresh;refresh();

async function checkUpdate(){try{const r=await fetch('/api/update');updateInfo=await r.json();if(!r.ok)throw Error(updateInfo.error);}catch(e){updateInfo={error:e.message};}if(page==='settings')render();}
function updatePrompt(){return `请在当前 WorkBuddy 项目更新云店+工作台，从 ${state.version} 更新到已检测的发布标签 ${updateInfo?.tag}。代码仓库：https://github.com/colaliang/yundian-ai-growth-workbench.git。客户数据目录：${state.projectRoot}。
先定位当前实际代码目录，读取规则和Git状态，核对新标签。备份工作台代码、客户growth-workspace和.codebuddy/skills及现有运行配置。不要读取或外传凭据。
在独立目录/分支获取新版本；对干净官方仓库先验证祖先关系再快进。存在本地提交或未提交改动时，先保存可恢复快照，在独立分支三方合并。不要reset --hard、强制覆盖或删除客户资料。
逐项比较技能，保留客户定制；已存在不同内容的技能不直接覆盖。非Git或缺少共同基线时，在独立目录验证新版本，仅迁移可明确识别的客户配置；无法判定的改动列出冲突并保留当前运行版本。
核查数据格式迁移，运行类型检查和回归测试，再切换并启动、读取客户数据验证。失败恢复原版本。已有本地版本高于目标时不要降级。只有客户已授权的代码更新可执行，无法安全合并时报告文件与原因，不宣称更新成功。最后报告旧/新版本、保留改动、备份位置和实际运行状态。`;}
document.addEventListener('change',e=>{if(e.target.id!=='avatar-file')return;const file=e.target.files?.[0];if(!file)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>262144){toast('请选择256KB以内的PNG/JPEG/WebP图片');return;}const reader=new FileReader();reader.onload=()=>save('avatar',{avatar:reader.result}).catch(e=>toast(e.message));reader.readAsDataURL(file);});
