'use strict';
const stages=[['market-research','市场调研','需求与竞争证据'],['product-opportunity','产品机会','机会与验证计划'],['site-and-content','建站与内容','网站、SEO与内容'],['acquisition','获客','渠道与实际线索'],['buyer-check','客户背调','匹配程度与风险'],['sales-feedback','销售反馈','跟进与成交结果'],['next-cycle','优化下一轮','反馈驱动新任务']];
let state,token,page='overview';const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const button=(text,action,id='',primary=false)=>`<button data-action="${action}" data-id="${esc(id)}" class="${primary?'primary':''}">${esc(text)}</button>`;
const label=s=>stages.find(x=>x[0]===s)?.[1]||s;const statuses={'ready':'待执行','needs-review':'待验收','completed':'已验收'};
function toast(s){$('#toast').textContent=s;$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',4000);}
async function refresh(){try{const r=await fetch('/api/state');if(!r.ok)throw Error('请使用 server.py 启动文件服务');state=await r.json();token=state.token;render();}catch(e){$('#main').innerHTML=`<div class="panel"><h1>项目资料未连接</h1><p>${esc(e.message)}</p><p>请运行：python server.py --root 客户项目目录 --port 8767</p></div>`;}}
async function save(action,payload){const r=await fetch('/api/save',{method:'POST',headers:{'Content-Type':'application/json','X-Workspace-Token':token},body:JSON.stringify({action,payload,revision:state.revision})});const value=await r.json();if(!r.ok)throw Error(value.error||'保存失败');state={...value,token,projectRoot:state.projectRoot};render();toast('已保存到项目文件');}
function heading(title,desc,actions=''){return `<div class="heading"><div><div class="eyebrow">YUNDIAN+ / AI GROWTH</div><h1>${title}</h1><p>${desc}</p></div><div class="actions">${actions}</div></div>`;}
function tasks(rows){return rows.length?rows.map(t=>`<div class="row"><div><h3>${esc(t.name)}</h3><p>${esc(label(t.stage))} · ${esc(t.cycleId)}</p></div><div class="actions"><span class="pill ${t.status==='completed'?'done':''}">${esc(statuses[t.status]||t.status)}</span>${button('查看任务','task',t.id)}</div></div>`).join(''):'<div class="empty">还没有任务<br>根据当前业务阶段，创建第一项获客工作。</div>';}
function render(){const nav=[['overview','增长总览'],['knowledge','企业知识库'],...stages.map(x=>[x[0],x[1]]),['artifacts','工作产物'],['settings','项目与设置']];$('#sidebar').innerHTML=`<div class="brand"><img src="brand.jpg" alt="云店+"><div><strong>云店+</strong><small>AI GROWTH</small></div></div><div class="project-label"><span class="muted">当前项目</span><strong>${esc(state.profile.company||'待创建企业知识库')}</strong><span class="muted">WorkBuddy 获客工作台</span></div><nav>${nav.map(([id,name],i)=>`<button data-action="nav" data-id="${id}" class="${page===id?'active':''}"><small>${i===0?'⌂':i===1?'▤':i<9?String(i-1).padStart(2,'0'):'·'}</small>${name}</button>`).join('')}</nav><footer>知识驱动 · 客户自主定制<br>真实文件保存 / v0.3</footer>`;
const setup=!state.profile.company?`<section class="panel setup"><div><h2>先建立企业知识库</h2><p>关联项目 → 添加企业资料 → 明确获客目标 → 启动第一项工作</p></div>${button('创建知识库','profile','',true)}</section>`:'';
let html='';
if(page==='overview'){html=heading('今天推进哪一步获客工作？',state.profile.goal||'先整理企业知识，再让 WorkBuddy 按业务阶段执行。',button('创建获客任务','new-task','',true))+setup+`<div class="path">${stages.map(([id,name,desc],i)=>`<button class="stage" data-action="nav" data-id="${id}"><span>${String(i+1).padStart(2,'0')}</span><strong>${name}</strong><small>${desc}</small></button>`).join('')}</div><div class="columns"><section class="panel"><h2>我的获客任务</h2>${tasks(state.tasks.filter(t=>t.status!=='completed'))}</section><section class="panel"><h2>共同的知识底座</h2><p>${state.profile.company?'企业资料已保存。每项任务使用同一组企业事实与来源。':'尚未填写企业、产品和目标市场。'}</p>${button('整理企业资料','profile')}<div class="row"><span>WorkBuddy 原生资料关联</span><span class="pill">待宿主验证</span></div><p class="note">先关联当前项目资料库或团队空间，再在 WorkBuddy 运行任务；文件保存不等于原生关联完成。</p></section></div>`;}
else if(page==='knowledge'){html=heading('企业知识库','七步获客工作共同使用的事实与来源。',button('添加知识资料','knowledge','',true)+button('编辑企业资料','profile'))+setup+state.knowledge.map(k=>`<section class="panel"><h2>${esc(k.path)}</h2><div class="knowledge">${esc(k.content)}</div></section>`).join('');}
else if(page==='settings'){html=heading('项目与设置','使用当前客户项目文件，保留 WorkBuddy 原生执行入口。')+`<section class="panel"><h2>实际文件目录</h2><div class="knowledge">${esc(state.projectRoot)}\ngrowth-workspace/</div><p class="note">启动时用 --root 选择客户项目；不同客户使用独立目录。</p><h2>WorkBuddy 项目 / 空间</h2><p>项目：${esc(state.profile.projectRef||'未填写')}<br>空间：${esc(state.profile.spaceRef||'未填写')}<br>关联状态：待宿主验证</p>${button('填写关联资料','profile')}<p class="note">在 WorkBuddy 项目中启用 yundian-growth-workbench 技能，上传知识文件到项目资料库。平台当前不自动创建云端空间，不保存供应商密钥。广告仅只读分析。</p></section>`;}
else if(page==='artifacts'){html=heading('工作产物','已保存的实际文件，验收与任务完成分别记录。')+`<section class="panel">${state.tasks.filter(t=>t.artifact).map(t=>`<div class="row"><div><h3>${esc(t.name)}</h3><p>${esc(t.artifact)}</p></div><a target="_blank" rel="noopener" href="/api/artifact/${encodeURIComponent(t.id)}.md">打开产物 ↗</a></div>`).join('')||'<div class="empty">暂无产物。完成 WorkBuddy 工作后，保存实际结果。</div>'}</section>`;}
else{html=heading(label(page),stages.find(x=>x[0]===page)?.[2]||'',button('定制阶段任务','new-task',page,true))+setup;if(page==='site-and-content'||page==='acquisition')html+=`<div class="service-links">${(page==='site-and-content'?['AI建站','Shopify独立站','WordPress定制建站','SEO/SEM/GEO','内容发布']:['主动开发','Facebook 报告','Google Ads 报告','社媒获客']).map(s=>button(s,'service',s)).join('')}</div>`;html+=`<section class="panel"><h2>阶段工作</h2>${tasks(state.tasks.filter(t=>t.stage===page))}</section>`;if(page==='sales-feedback')html+=`<section class="panel"><div class="heading"><h2>真实销售反馈</h2>${button('记录反馈','feedback','',true)}</div>${state.feedback.map(f=>`<div class="row"><div><h3>${esc(f.leadId)} · ${esc(f.result)}</h3><p>${esc(f.source)} / ${esc(f.reason)}</p><p>下一步：${esc(f.next||'待定')}</p></div></div>`).join('')||'<div class="empty">暂无实际反馈。记录联系、报价、成交或拒绝原因。</div>'}</section>`;if(page==='next-cycle')html+=`<section class="panel"><h2>下一轮优化依据</h2><p>${state.feedback.length?`已有 ${state.feedback.length} 条客户反馈，可关联渠道与线索调整下一轮任务。`:'等待实际线索及销售反馈。可以建立验证假设，不以预测冒充获客结果。'}</p></section>`;}
$('#main').innerHTML=html+'<p class="footer-note">市场调研 → 产品机会 → 建站与内容 → 获客 → 客户背调 → 销售反馈 → 优化下一轮</p>';}
function modal(title,body){$('#dialog-title').textContent=title;$('#dialog-body').innerHTML=body;$('#dialog').showModal();}
function field(name,title,value='',area=false){return `<label>${esc(title)}${area?`<textarea name="${name}">${esc(value)}</textarea>`:`<input name="${name}" value="${esc(value)}">`}</label>`;}
function form(title,body,action,extra={}){modal(title,`<form>${body}<div class="error" role="alert"></div><div class="actions"><button type="submit" class="primary">保存</button></div></form>`);$('#dialog-body form').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button[type=submit]');b.disabled=true;try{await save(action,{...Object.fromEntries(new FormData(e.target)),...extra});$('#dialog').close();}catch(err){e.target.querySelector('.error').textContent=err.message;}finally{b.disabled=false;}};}
function prompt(t){return `使用 yundian-growth-workbench 技能，在当前 WorkBuddy 客户项目执行真实任务。\n项目目录：${state.projectRoot}\n企业：${state.profile.company}\n获客目标：${state.profile.goal}\n阶段：${label(t.stage)}\n轮次：${t.cycleId}\n任务：${t.name}\n输入/上游产物：${t.inputs||'先读取 knowledge 目录，缺失则补资料'}\n步骤/工具：${t.instructions||'按客户目标定制实际工作流'}\n验收：${t.acceptance||'产物可读、来源可追溯；未知事实标记待确认'}\n将实际产物写入 growth-workspace/artifacts/${t.id}.md，并更新任务记录。执行失败不得模拟成功。广告只读；外部动作按实际授权。原生项目资料关联需先在宿主验证。\n完成后回到工作台保存产物内容并记录验收。`;}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const {action,id}=b.dataset;
if(action==='nav'){page=id;render();$('#sidebar').classList.remove('open');}
if(action==='profile'){const p=state.profile;form('企业知识库与项目资料',`<div class="form-grid">${[['company','企业名称'],['products','产品 / 服务'],['markets','目标市场'],['persona','买家画像'],['goal','获客目标'],['brand','品牌与业务约束'],['source','资料来源 / 文件路径'],['projectRef','WorkBuddy 项目名称 / 链接'],['spaceRef','关联空间名称 / 链接']].map(([k,v])=>field(k,v,p[k]||'',k==='goal'||k==='source')).join('')}</div><p class="note">填写名称/链接不会自动关联云端空间；需在 WorkBuddy 中完成并验证。</p>`,'profile');}
if(action==='new-task'||action==='service'){const stage=stages.some(x=>x[0]===id)?id:stages.some(x=>x[0]===page)?page:'market-research';form('定制获客任务',`${field('name','任务名称',action==='service'?id:'')}<label>获客阶段<select name="stage">${stages.map(([k,n])=>`<option value="${k}" ${k===stage?'selected':''}>${n}</option>`).join('')}</select></label>${field('cycleId','轮次标识','cycle-1')}${field('inputs','输入来源 / 上游产物','',true)}${field('instructions','工作步骤 / 所需工具','',true)}${field('acceptance','验收规则','',true)}`,'task');}
if(action==='knowledge')form('添加真实知识资料',field('title','资料标题')+field('content','实际资料内容','',true)+field('source','来源 URL / 文件路径'),'knowledge');
if(action==='feedback')form('记录真实销售反馈',`${field('leadId','稳定线索标识')}${field('source','获客渠道 / 上游产物')}${field('cycleId','轮次标识','cycle-1')}${field('result','实际联系 / 报价 / 成交结果')}${field('reason','有效或无效原因','',true)}${field('next','下一轮改进建议','',true)}`,'feedback');
if(action==='task'){const t=state.tasks.find(t=>t.id===id);modal(t.name,`<p>${esc(label(t.stage))} · ${esc(statuses[t.status])}</p><div class="prompt">${esc(prompt(t))}</div><p class="note">复制指令到 WorkBuddy 当前项目执行；这里不会模拟调用模型。</p><div class="actions">${button('复制 WorkBuddy 指令','copy',id,true)}${button('保存实际产物','artifact',id)}${t.artifact?button('记录验收','review',id):''}</div>`);}
if(action==='copy'){navigator.clipboard.writeText(prompt(state.tasks.find(t=>t.id===id))).then(()=>toast('指令已复制，请在 WorkBuddy 当前项目执行')).catch(()=>toast('请手动选中并复制任务指令'));}
if(action==='artifact'){form('保存实际工作产物',field('content','产物内容（含来源与结果）','',true),'artifact',{id});}
if(action==='review'){form('记录客户验收',field('review','实际验收依据','',true),'review',{id});}
});$('#close').onclick=()=>$('#dialog').close();$('#menu').onclick=()=>$('#sidebar').classList.toggle('open');$('#refresh').onclick=refresh;refresh();

