import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {createSnapshot,restoreSnapshot,setOnlineBackup} from '../src/backup/service.ts';
import {inspectUpdate} from '../src/updates/check.ts';
function fixture(){const root=fs.mkdtempSync(path.join(os.tmpdir(),'backup-test-'));fs.mkdirSync(path.join(root,'growth-workspace'));fs.writeFileSync(path.join(root,'growth-workspace/workspace.json'),JSON.stringify({workspaceId:'customer-a',schemaVersion:3,contractVersion:2,backup:{enabled:false}}));fs.writeFileSync(path.join(root,'growth-workspace/output.bin'),Buffer.from([0,255,1]));return root;}
test('snapshot validates binary, preserves both conflicts and pre-restore backup',()=>{const root=fixture();try{const snap=createSnapshot(root);fs.writeFileSync(path.join(root,'growth-workspace/output.bin'),'local');const result=restoreSnapshot(root,snap);assert.equal(fs.readFileSync(path.join(root,'growth-workspace/output.bin'),'utf8'),'local');assert.equal(result.conflicts.length,1);assert.deepEqual(fs.readFileSync(result.conflicts[0].incoming),Buffer.from([0,255,1]));assert.ok(fs.existsSync(result.backupPath));}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('invalid checksum, traversal, duplicate and foreign customer make no writes',()=>{const root=fixture();try{for(const mutate of [(s:any)=>s.files[0].checksum='bad',(s:any)=>s.files[0].path='../escape',(s:any)=>s.workspaceId='other',(s:any)=>s.files.push(s.files[0])]){const s=createSnapshot(root);mutate(s);assert.throws(()=>restoreSnapshot(root,s));assert.equal(fs.existsSync(path.join(root,'.workbench-backups')),false);}}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('unauthenticated online backup cannot enable; disabling never calls remote',async()=>{const root=fixture();try{assert.equal(JSON.parse(fs.readFileSync(path.join(root,'growth-workspace/workspace.json'),'utf8')).backup.enabled,false);await assert.rejects(setOnlineBackup(root,true));await assert.rejects(setOnlineBackup(root,true,{verifyIsolation:async()=>false} as any));await setOnlineBackup(root,false);assert.equal(JSON.parse(fs.readFileSync(path.join(root,'growth-workspace/workspace.json'),'utf8')).backup.enabled,false);}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('update inspection distinguishes code, customer and customized skills without mutation',()=>{const root=fixture();try{fs.mkdirSync(path.join(root,'.codebuddy/skills/custom'),{recursive:true});fs.writeFileSync(path.join(root,'.codebuddy/skills/custom/SKILL.md'),'custom');const result=inspectUpdate(root);assert.equal(result.automaticUpdateAllowed,false);assert.ok(result.customerPaths.includes('growth-workspace'));assert.ok(result.customSkills.includes('custom'));assert.equal(fs.readFileSync(path.join(root,'.codebuddy/skills/custom/SKILL.md'),'utf8'),'custom');}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('symlink destinations and inconsistent manifest fail before backup',()=>{const root=fixture(),outside=fs.mkdtempSync(path.join(os.tmpdir(),'backup-outside-'));try{const snap=createSnapshot(root);fs.mkdirSync(path.join(outside,'target'));fs.symlinkSync(path.join(outside,'target'),path.join(root,'growth-workspace/link'),'junction');assert.throws(()=>createSnapshot(root));const row={...snap.files[0],path:'growth-workspace/link/file'};assert.throws(()=>restoreSnapshot(root,{...snap,files:[...snap.files,row]}));assert.equal(fs.existsSync(path.join(root,'.workbench-backups')),false);}finally{fs.rmSync(root,{recursive:true,force:true});fs.rmSync(outside,{recursive:true,force:true});}});
test('file-parent collision is rejected before any write',()=>{const root=fixture();try{const snap=createSnapshot(root);const row=snap.files.find(f=>f.path.endsWith('output.bin'))!;assert.throws(()=>restoreSnapshot(root,{...snap,files:[...snap.files,{...row,path:row.path+'/child'}]}));assert.equal(fs.existsSync(path.join(root,'.workbench-backups')),false);}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('workspace file scope and owned JSON scope are validated independently of checksums',async()=>{const {createHash}=await import('node:crypto');const root=fixture();try{for(const target of ['growth-workspace/workspace.json','growth-workspace/tasks/foreign.json']){const snap=createSnapshot(root),bytes=Buffer.from(JSON.stringify({workspaceId:'foreign',schemaVersion:3,contractVersion:2,backup:{enabled:false}}));const row={path:target,checksum:createHash('sha256').update(bytes).digest('hex'),data:bytes.toString('base64')};snap.files=snap.files.filter(f=>f.path!==target);snap.files.push(row);assert.throws(()=>restoreSnapshot(root,snap));assert.equal(fs.existsSync(path.join(root,'.workbench-backups')),false);}}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('CLI snapshot and update inspection operate on existing directories without initialization',async()=>{const {execFileSync}=await import('node:child_process');const root=fixture();try{const cli=path.resolve('scripts/workbench.mjs'),output=path.join(root,'snapshot.json');execFileSync(process.execPath,[cli,'--root',root,'--command','backup-export','--output',output]);assert.ok(fs.existsSync(output));execFileSync(process.execPath,[cli,'--root',root,'--command','backup-restore','--payload',output]);const result=JSON.parse(execFileSync(process.execPath,[cli,'--root',root,'--command','update-inspect'],{encoding:'utf8'}));assert.equal(result.automaticUpdateAllowed,false);assert.equal(fs.existsSync(path.join(root,'growth-workspace/workbench.json')),false);}finally{fs.rmSync(root,{recursive:true,force:true});}});
import crypto from 'node:crypto';
function treeBytes(root:string):Record<string,string>{const result:Record<string,string>={};function walk(folder:string){for(const entry of fs.readdirSync(folder,{withFileTypes:true})){const file=path.join(folder,entry.name);if(entry.isDirectory())walk(file);else result[path.relative(root,file)]=fs.readFileSync(file).toString('base64');}}walk(root);return result;}
function incoming(snap:any,relative:string,value:any){const bytes=Buffer.from(typeof value==='string'?value:JSON.stringify(value));snap.files=snap.files.filter((f:any)=>f.path.toLowerCase()!==relative.toLowerCase());snap.files.push({path:relative,data:bytes.toString('base64'),checksum:crypto.createHash('sha256').update(bytes).digest('hex')});}
test('every owned JSON family preflights corrupt JSON and leaves entire tree unchanged',()=>{const root=fixture();try{for(const relative of ['workbench.json','workflows/x.json','audits/x.json','knowledge-confirmations/x.json','daily-decisions/x.json','schedule-occurrences/x.json','delivery-programs/x.json']){const snap=createSnapshot(root),before=treeBytes(root);incoming(snap,'growth-workspace/'+relative,'{');assert.throws(()=>restoreSnapshot(root,snap),relative);assert.deepEqual(treeBytes(root),before);}}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('case aliases, absent or falsy scopes, wrong shapes and nested foreign scopes reject without writes',()=>{const root=fixture();try{for(const [relative,value] of [['Tasks/foreign.JSON',{id:'x',workspaceId:'foreign'}],['workflows/x.json',{id:'x',workspaceId:'foreign'}],['tasks/new.json',{}],['tasks/new.json',[]],['tasks/new.json',{id:'x',workspaceId:''}],['delivery-programs/new.json',{id:'x'}],['receipts/new.json',{workspaceId:'customer-a',taskId:'x',receiptId:'r',receipt:{workspaceId:'foreign'}}],['workbench.json',{profile:{},tasks:[],feedback:[],settings:{workspaceId:'foreign'}}]] as const){const snap=createSnapshot(root),before=treeBytes(root);incoming(snap,'growth-workspace/'+relative,value);assert.throws(()=>restoreSnapshot(root,snap),relative);assert.deepEqual(treeBytes(root),before);}}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('legacy missing scope needs matching migration provenance; new missing or falsy scopes stay rejected',()=>{const root=fixture();try{const manifest=JSON.parse(fs.readFileSync(path.join(root,'growth-workspace/workspace.json'),'utf8'));manifest.legacySchemaVersion=3;fs.writeFileSync(path.join(root,'growth-workspace/workspace.json'),JSON.stringify(manifest));const snap=createSnapshot(root),legacy={id:'legacy-task',stage:'market-research',name:'historical',status:'ready',createdAt:'2026-01-01'};incoming(snap,'growth-workspace/tasks/legacy.json',legacy);let before=treeBytes(root);assert.throws(()=>restoreSnapshot(root,snap));assert.deepEqual(treeBytes(root),before);incoming(snap,'growth-workspace/migration-backups/captured/workspace.json',{schemaVersion:3,workspaceId:'customer-a'});incoming(snap,'growth-workspace/migration-backups/captured/tasks/legacy.json',legacy);const result=restoreSnapshot(root,snap);assert.ok(result.restored.includes('growth-workspace/tasks/legacy.json'));const falsy=createSnapshot(root);incoming(falsy,'growth-workspace/tasks/legacy.json',{...legacy,workspaceId:''});incoming(falsy,'growth-workspace/migration-backups/captured/tasks/legacy.json',{...legacy,workspaceId:''});before=treeBytes(root);assert.throws(()=>restoreSnapshot(root,falsy));assert.deepEqual(treeBytes(root),before);}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('recognized families reject wrong object and array shapes before creating backups',()=>{const root=fixture();try{for(const family of ['workflows','audits','knowledge-confirmations','daily-decisions','schedule-occurrences','delivery-programs','records','feedback','schedules','reviews','artifacts'])for(const value of [{},[],null,{workspaceId:'customer-a',id:'x'}]){const snap=createSnapshot(root),before=treeBytes(root);incoming(snap,'growth-workspace/'+family+'/bad.JSON',value);assert.throws(()=>restoreSnapshot(root,snap),family);assert.deepEqual(treeBytes(root),before);}}finally{fs.rmSync(root,{recursive:true,force:true});}});
