import test from 'node:test';
import assert from 'node:assert/strict';
// @ts-ignore Browser ES module is exercised directly by Node and Edge.
import * as view from '../web/views/content-plan.js';
const item={id:'i',title:'<标题>',text:'实际正文',contentHash:'h',approvedHash:'h',reviewStatus:'approved',channelIds:['c'],remoteMediaIds:[],assetRefs:['local.png'],timezone:'Asia/Shanghai',plannedAt:null,contentRevision:2};
test('publish UI binds approval, caps and required remote media without blocking text channels',()=>{assert.equal(typeof view.publishEligibility,'function');const cfg={configured:true,maxCreditsPerPost:2,maxCreditsPerDay:3};assert.equal(view.publishEligibility(item,cfg,[{id:'c',platform:'linkedin'}],[]),'');assert.match(view.publishEligibility(item,cfg,[{id:'c',platform:'instagram'}],[]),/远端/);assert.match(view.publishEligibility({...item,approvedHash:'old'},cfg,[],[]),/批准/);assert.match(view.publishEligibility(item,{...cfg,maxCreditsPerDay:0},[],[]),/上限/);});
test('confirmation and receipt expose exact body caps status and conservative unknown cost',()=>{assert.equal(typeof view.publishDialog,'function');const html=view.publishDialog(item,{id:'confirmation',contentHash:'h',channelIds:['c'],mode:'immediate',plannedAt:null,maxCredits:1,balance:7,expiresAt:'2030-01-01'});for(const text of ['实际正文','c','7','1','Asia/Shanghai','data-consent','data-publish-submit'])assert.ok(html.includes(text),text);const receipt=view.publishReceipt({id:'a',status:'partial',postId:'p',reservedCredits:2,actualCredits:null,results:[{channelId:'c',status:'published'},{channelId:'d',status:'unknown',pending:true}]});for(const text of ['partial','published','pending','unknown','保守预留','尚未'])assert.ok(receipt.includes(text),text);assert.ok(!html.includes('apiKey'));});

test('social receipt projection follows actual source task stage only',()=>{const items=[{id:'content',sourceTaskId:'t1'},{id:'social',sourceTaskId:'t2'},{id:'unlinked',sourceTaskId:null}];const tasks=[{id:'t1',stage:'content-operations'},{id:'t2',stage:'social-media'}];assert.deepEqual(view.receiptItemsForModule(items,tasks,'social-media').map((x:any)=>x.id),['social']);assert.equal(view.receiptItemsForModule(items,tasks,'content-operations').length,3);assert.equal(view.receiptItemsForModule(items,tasks,'market-research').length,0);});

test('unknown without remote ID offers manual verification and no ineffective refresh',()=>{const html=view.publishReceipt({id:'lost',status:'unknown',postId:null,reservedCredits:1,actualCredits:null,channelIds:['c'],results:[]});assert.ok(html.includes('data-publish-manual'));assert.ok(html.includes('https://socialmedia.ydjia.com'));assert.ok(html.includes('刷新无法'));assert.ok(!html.includes('data-publish-refresh'));});
test('publication recovery reads durable attempts and items instead of cached truth',async()=>{assert.equal(typeof view.readPublicationState,'function');const calls:string[]=[];const data=await view.readPublicationState(async(p:string)=>{calls.push(p);return p.endsWith('attempts')?{attempts:[{id:'durable',postId:null,status:'unknown'}]}:{items:[{id:'i',status:'unknown'}],revision:8};});assert.deepEqual(calls,['/api/publisher/attempts','/api/content/items']);assert.equal(data.attempts[0].id,'durable');assert.equal(data.items[0].status,'unknown');assert.equal(data.revision,8);});
