import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {getModuleServices,createDeliveryProgram,deliveryProgress,shareSelection} from '../src/domain/delivery.ts';
import {FileWorkspace} from '../server.ts';
test('confirmed expert scoped to supported modules, missing modules retain skills',()=>{assert.equal(getModuleServices('market-research').length,0);const s=getModuleServices('seo');assert.equal(s[0].expert.name,'搞跨境的可乐哥');assert.equal(s[0].expert.contact,'13631179943');assert.equal(s[0].paid,true);assert.equal('price' in s[0],false);assert.equal(getModuleServices('unknown').length,0);});
test('real instance and latest current review only',()=>{const p=createDeliveryProgram('site-search','w');assert.equal(p.taskIds.length,0);const task={id:'t',workspaceId:'w',stage:'site-and-content',status:'completed',artifactIds:['a']};const a={id:'a',workspaceId:'w',taskId:'t',contentHash:'h'};const review={id:'r',workspaceId:'w',taskId:'t',artifactId:'a',contentHash:'h',decision:'accepted',sequence:1,valid:true};p.taskIds=['t'];assert.equal(deliveryProgress(p,[task],[a],[review]).completed,1);assert.equal(deliveryProgress(p,[task],[{...a,contentHash:'changed'}],[review]).completed,0);assert.equal(deliveryProgress(p,[task],[a],[review,{...review,sequence:2,decision:'rejected'}]).completed,0);assert.equal(deliveryProgress(p,[{...task,workspaceId:'other'}],[a],[review]).completed,0);});
test('sharing requires explicit selected local scope, no automatic contact data',()=>{const a={id:'a',workspaceId:'w',taskId:'t',summary:'chosen'};assert.deepEqual(shareSelection('w',[],[a]),[]);assert.throws(()=>shareSelection('w',['other'],[a]));assert.deepEqual(shareSelection('w',['a'],[a]),[a]);});
test('program persists actual tasks and workflows and survives reload',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'delivery-'));try{let store=new FileWorkspace(root);const save=(action:string,payload:any)=>store.save({action,payload,revision:store.load().revision});save('profile',{company:'Fixture',goal:'Acquire'});save('delivery-create',{templateId:'site-search'});store=new FileWorkspace(root);const state=store.load(),p=state.deliveryPrograms[0];assert.equal(p.workspaceId,state.workspace.workspaceId);assert.equal(p.taskIds.length,2);assert.equal(p.progress.completed,0);for(const id of p.taskIds){assert.ok(state.tasks.some((t:any)=>t.id===id));assert.ok(fs.existsSync(path.join(store.base,'workflows',id+'.json')));}assert.throws(()=>save('delivery-create',{templateId:'unknown'}));}finally{fs.rmSync(root,{recursive:true,force:true});}});

test('persisted program progress follows real current artifact reviews and stale revisions reject',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'delivery-progress-'));try{const store=new FileWorkspace(root);const save=(action:string,payload:any)=>store.save({action,payload,revision:store.load().revision});save('profile',{company:'Fixture',goal:'Evidence'});const old=store.load().revision;save('delivery-create',{templateId:'site-search'});assert.throws(()=>store.save({action:'delivery-create',payload:{templateId:'site-search'},revision:old}));const t=store.load().tasks[0];save('artifact',{id:t.id,content:'Actual first version'});let state=store.load();const a=state.artifacts.find((a:any)=>a.taskId===t.id);save('review',{id:t.id,artifactId:a.id,contentHash:a.contentHash,decision:'accepted',review:'Fixture customer checked actual result'});assert.equal(store.load().deliveryPrograms[0].progress.completed,1);assert.ok(store.load().deliveryPrograms[0].artifactIds.includes(a.id));fs.writeFileSync(path.resolve(root,a.path),'Actual changed version');assert.equal(store.load().deliveryPrograms[0].progress.completed,0);}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('full acquisition template creates actual supported stages with no expert requirement',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'delivery-full-'));try{const store=new FileWorkspace(root);store.save({action:'profile',payload:{company:'Fixture',goal:'Acquire'},revision:store.load().revision});store.save({action:'delivery-create',payload:{templateId:'full-acquisition'},revision:store.load().revision});const state=store.load(),p=state.deliveryPrograms[0];assert.equal(p.taskIds.length,14);assert.equal(p.progress.total,14);assert.equal(p.progress.completed,0);for(const stage of ['market-research','product-opportunity','site-and-content','seo','geo','content-operations','social-media','facebook-ads','google-ads','acquisition','email-outreach','buyer-check','sales-feedback','next-cycle'])assert.ok(state.tasks.some((t:any)=>t.stage===stage));assert.equal(getModuleServices('buyer-check').length,0);}finally{fs.rmSync(root,{recursive:true,force:true});}});
