import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {FileWorkspace} from '../server.ts';
import {registerHostReceipt} from '../src/scheduling/service.ts';
import {createSnapshot,restoreSnapshot} from '../src/backup/service.ts';
import {recommendDaily,dailyContext} from '../src/domain/daily-actions.ts';
// @ts-ignore browser JavaScript module has no declaration
import {resultsView} from '../web/views/results.js';
function fixture(fn:(store:FileWorkspace)=>void){const root=fs.mkdtempSync(path.join(os.tmpdir(),'final-fix-'));try{fn(new FileWorkspace(root));}finally{fs.rmSync(root,{recursive:true,force:true});}}
const save=(s:FileWorkspace,action:string,payload:any={})=>s.save({action,payload,revision:s.load().revision});
function helper(s:FileWorkspace,t:any,python=false){const report=path.join(s.root,'growth-workspace/artifacts',t.id+'.md');if(!fs.existsSync(report))fs.writeFileSync(report,'# Actual fixture report');const script=path.join(s.root,'.codebuddy/skills/yundian-growth-workbench/scripts/submit_result.'+(python?'py':'mjs'));return ()=>execFileSync(python?'python':process.execPath,[script,'--application',t.applicationRoot||process.cwd(),'--root',s.root,'--task',t.id,'--file',report],{encoding:'utf8',stdio:'pipe'});}
test('exact installed default invocation uses canonical metadata and identical receipts are idempotent across Node/Python',()=>fixture(s=>{save(s,'profile',{company:'Fixture',goal:'Research'});save(s,'install-skills');save(s,'task',{stage:'market-research',name:'Research'});const t=s.load().tasks[0];const node=helper(s,t);const command=t.invocation.split('\n').find((v:string)=>v.startsWith('node "'))!;assert.ok(command.includes('.codebuddy/skills/yundian-growth-workbench/scripts/submit_result.mjs'));assert.ok(command.includes(path.join(s.root,'growth-workspace/artifacts',t.id+'.md').replaceAll('\\','/')));const parts=command.match(/^node "([^"]+)" --root "([^"]+)" --task ([a-f0-9]+) --file "([^"]+)" --application "([^"]+)"$/)!;assert.ok(parts);execFileSync(process.execPath,[parts[1],'--root',parts[2],'--task',parts[3],'--file',parts[4],'--application',parts[5]],{stdio:'pipe'});let state=s.load();assert.equal(state.tasks[0].status,'needs-review');assert.equal(state.artifacts.length,1);assert.ok(state.tasks[0].latestReceiptKey);assert.equal(state.artifacts[0].executor,'manual');assert.equal(state.artifacts[0].verification,'unverified');const revision=state.revision;node();assert.equal(s.load().revision,revision);helper(s,t,true)();assert.equal(s.load().revision,revision);}));
test('installed helper cannot mutate unauthorized scheduled publication or terminal occurrences',()=>{for(const mode of ['publish','failed','cancelled'])fixture(s=>{save(s,'profile',{company:'Fixture',goal:'Research'});save(s,'install-skills');save(s,'schedule-create',{name:'Daily',stage:'market-research',operation:mode==='publish'?'publish':'draft'});const schedule=s.load().schedules[0];s.put(path.join(s.base,'schedules',schedule.id+'.json'),registerHostReceipt(schedule,{workspaceId:schedule.workspaceId,scheduleId:schedule.id,action:'create',hostTaskId:'fixture',source:'test only',evidence:'fixture',status:'enabled'},()=>true));save(s,'schedule-occurrence',{id:schedule.id,scheduledAt:'2026-10-08T01:00:00Z'});const t=s.load().tasks[0];if(mode!=='publish')s.applyReceipt(t.id,{receiptId:'terminal',taskId:t.id,workspaceId:t.workspaceId,skillVersion:t.skillVersion,executor:'fixture',status:mode},s.load().revision);const node=helper(s,t),revision=s.load().revision;assert.throws(node);assert.equal(s.load().revision,revision);assert.equal(s.load().tasks[0].status,mode==='publish'?'needs-input':mode);assert.equal(s.load().artifacts.length,0);assert.throws(helper(s,t,true));assert.equal(s.load().revision,revision);});});
test('canonical task missing actual application fails honestly without raw writes',()=>fixture(s=>{save(s,'profile',{company:'Fixture',goal:'Research'});save(s,'task',{stage:'market-research',name:'Research'});save(s,'install-skills');const t=s.load().tasks[0];delete t.applicationRoot;s.put(path.join(s.base,'tasks',t.id+'.json'),t);const node=helper(s,t),revision=s.load().revision;assert.throws(node);assert.equal(s.load().revision,revision);}));
test('unsafe restored artifact URLs reject before backups; legacy rendering retains escaped text and controls',()=>fixture(s=>{for(const url of ['javascript:alert(1)','data:text/html,<script>alert(1)</script>']){const snapshot=createSnapshot(s.root);const body=Buffer.from(JSON.stringify({id:'fixture',workspaceId:snapshot.workspaceId,taskId:'task',module:'market-research',skillVersion:'1',url,summary:'Fixture',sources:[],gaps:[],nextSteps:[],verification:'unverified'}));snapshot.files.push({path:'growth-workspace/artifacts/fixture.json',data:body.toString('base64'),checksum:createHash('sha256').update(body).digest('hex')});const revision=s.load().revision;assert.throws(()=>restoreSnapshot(s.root,snapshot));assert.equal(s.load().revision,revision);assert.equal(fs.existsSync(path.join(s.root,'.workbench-backups')),false);const esc=(v:any)=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');const state={tasks:[],reviews:[],artifacts:[{id:'fixture',taskId:'task',url,summary:'Fixture'}]};const html=resultsView({state,heading:()=>'',button:(label:string)=>label,esc});assert.ok(!html.includes('href="'+url));assert.ok(html.includes(esc(url)));assert.ok(html.includes('重新执行新批次'));state.artifacts[0].url='https://example.test/report';assert.ok(resultsView({state,heading:()=>'',button:()=>'',esc}).includes('href="https://example.test/report"'));}}));
test('complete profile without tasks gets exactly one concrete research suggestion',()=>{const profile={company:'Fixture',products:'Lighting',markets:'US',persona:'Retail buyer',goal:'Find qualified buyers'};const context=dailyContext({workspace:{workspaceId:'fixture'},profile,tasks:[],feedback:[],artifacts:[{summary:'Client supplied brief'}],skills:{'market-research':{id:'research'}}});const rows=recommendDaily(context,'2026-10-08');assert.equal(rows.length,1);assert.equal(rows[0].stage,'market-research');assert.ok(rows[0].inputs.includes('Lighting'));assert.ok(rows[0].inputs.includes('Client supplied brief'));});

test('installed helper rejects data-supplied malformed application before import',()=>fixture(s=>{save(s,'profile',{company:'Fixture',goal:'Research'});save(s,'task',{stage:'market-research',name:'Research'});save(s,'install-skills');const t=s.load().tasks[0],actual=t.applicationRoot;t.applicationRoot=path.join(s.base,'artifacts');s.put(path.join(s.base,'tasks',t.id+'.json'),t);fs.writeFileSync(path.join(s.base,'artifacts/server.ts'),"throw Error('MUST NOT IMPORT');");const report=path.join(s.root,'report.md');fs.writeFileSync(report,'Actual fixture');const revision=s.load().revision;assert.throws(()=>execFileSync(process.execPath,[path.join(s.root,'.codebuddy/skills/yundian-growth-workbench/scripts/submit_result.mjs'),'--application',actual,'--root',s.root,'--task',t.id,'--file',report],{stdio:'pipe'}));assert.equal(s.load().revision,revision);}));

test('installed scheduled draft receipt is canonical and idempotent without inventing actual execution time',()=>fixture(s=>{save(s,'profile',{company:'Fixture',goal:'Research'});save(s,'install-skills');save(s,'schedule-create',{name:'Daily',stage:'market-research'});const schedule=s.load().schedules[0];s.put(path.join(s.base,'schedules',schedule.id+'.json'),registerHostReceipt(schedule,{workspaceId:schedule.workspaceId,scheduleId:schedule.id,action:'create',hostTaskId:'fixture',source:'test only',evidence:'fixture',status:'enabled'},()=>true));save(s,'schedule-occurrence',{id:schedule.id,scheduledAt:'2026-10-08T01:00:00Z'});const t=s.load().tasks[0],node=helper(s,t);const result=JSON.parse(node()),state=s.load();assert.equal(state.scheduleOccurrences[0].status,'needs-review');assert.equal(state.scheduleOccurrences[0].result,result.receiptId);assert.equal(state.scheduleOccurrences[0].actualAt,null);assert.equal(state.artifacts[0].executedAt,null);const revision=state.revision;node();assert.equal(s.load().revision,revision);}));
