import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {FileWorkspace} from '../server.ts';
import {ContentService} from '../src/content/service.ts';
import {PublicationService} from '../src/publishing/service.ts';
import {CrmService} from '../src/crm/service.ts';
import {createSnapshot,restoreSnapshot} from '../src/backup/service.ts';
import {artifactsForModule,MODULES} from '../src/navigation/modules.ts';
import type {PublisherPort} from '../src/publishing/contracts.ts';
function mockPublisher(timeout=false){let creates=0,publishes=0;const publisher:PublisherPort={listChannels:async()=>[{id:'fixture-channel',name:'Fixture',platform:'facebook',isActive:true}],listMedia:async()=>[{id:'fixture-media',mimeType:'image/png',url:'https://example.invalid/media.png'}],getBalance:async()=>({balance:10}),createPost:async input=>{creates++;assert.deepEqual(input.mediaIds,['fixture-media']);return {id:'fixture-post',status:'draft',scheduledAt:null,postChannels:[]};},publishPost:async postId=>{publishes++;if(timeout)throw Error('fixture timeout');return {postId,results:[{channelId:'fixture-channel',status:'published',platformPostId:'fixture-platform-post',url:'https://example.invalid/post'}]};},getPost:async()=>{throw Error('unresolved');}};return {publisher,counts:()=>({creates,publishes})};}
test('same customer skill receipt → project result → approved mock publication → CRM actual feedback → next cycle survives all-family backup',async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'module-closed-loop-'));try{const store=new FileWorkspace(root),save=(action:string,payload:any)=>store.save({action,payload,revision:store.load().revision});save('profile',{company:'Fixture',products:'Fixture',markets:'Fixture',persona:'Fixture',goal:'Actual evidence'});save('delivery-create',{templateId:'site-search'});const legacy=store.createTask({name:'Legacy SEO/GEO',stage:'seo-geo'},store.load().revision);store.write(path.join(store.base,'artifacts',legacy.id+'.md'),'# Legacy markdown retained');fs.writeFileSync(path.join(store.base,'artifacts','legacy.bin'),Buffer.from([0,255,13,10]));const task=store.createTask({name:'Content fixture',stage:'content-operations',cycleId:'cycle-fixture'},store.load().revision);fs.writeFileSync(path.join(root,'content-fixture.md'),'Customer reviewed public fixture');store.applyReceipt(task.id,{receiptId:'fixture-receipt',taskId:task.id,workspaceId:task.workspaceId,skillVersion:task.skillVersion,executor:'WorkBuddy',status:'needs-review',artifacts:[{path:'content-fixture.md',sources:['fixture public fact']}]},store.load().revision);const artifact=artifactsForModule(store.load(),'content-operations')[0];assert.equal(artifact.taskId,task.id);store.reviewArtifact(task.id,artifact.contentHash!,'accepted','Fixture customer reviewed',store.load().revision,artifact.id);
const content=new ContentService(store),item=content.create({title:'Fixture public content',text:'Public fact only',channelIds:['fixture-channel'],remoteMediaIds:['fixture-media'],sourceTaskId:task.id,cycleId:'cycle-fixture'});content.approve(item.id,item.contentHash);const mock=mockPublisher(),publication=new PublicationService(store,()=>({publisher:mock.publisher,secrets:{apiKey:'fixture-only',maxCreditsPerPost:1,maxCreditsPerDay:2}}));const confirmation=await publication.preparePublish(item.id,{channelIds:item.channelIds,mode:'immediate',plannedAt:null});const attempt=await publication.submitPublish(item.id,confirmation.id);assert.equal(attempt.status,'published');assert.equal(attempt.actualCredits,null);assert.equal(attempt.budgetDay,new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(attempt.createdAt)));assert.deepEqual(mock.counts(),{creates:1,publishes:1});
const crm=new CrmService(store),company=crm.createCompany({name:'Fixture actual buyer',source:'Fixture actual inquiry '+attempt.results[0].url}),contact=crm.createContact({companyId:company.id,source:'Fixture supplied',email:'fixture@example.invalid'}),lead=crm.createLead({companyId:company.id,contactIds:[contact.id],source:'Fixture inquiry',sourceProjectId:'content-operations'});const buyerTask=store.createTask({name:'Verify actual inquiry',stage:'buyer-check',sourceLeadId:lead.id,cycleId:'cycle-fixture'},store.load().revision);crm.recordFollowUp({leadId:lead.id,time:'2026-10-10T00:00:00Z',method:'actual fixture reply',content:'Customer confirmed actual reply',result:'Requested specification',taskIds:[buyerTask.id],nextFollowUpAt:'2099-10-10T00:00:00Z'});save('feedback',{leadId:lead.id,cycleId:'cycle-fixture',result:'Actual requested specification',source:'Fixture actual followup',next:'Clarify specification'});const feedback=store.load().feedback.at(-1);crm.linkFeedback(feedback.id,lead.id);const daily=store.load().dailyActions.find((row:any)=>row.id==='feedback:'+feedback.id);assert.ok(daily);save('daily-create',{id:daily.id});assert.ok(store.load().tasks.some((t:any)=>t.stage==='next-cycle'&&t.cycleId==='cycle-fixture'));assert.equal(crm.crmLeadContext(lead.id).contacts[0].id,contact.id);assert.equal(crm.listLeads()[0].stage,'new');
const snapshot=createSnapshot(root),families=['content-items','publish-attempts','publish-confirmations','crm-companies','crm-contacts','crm-leads','crm-followups','crm-feedback-links'];for(const family of families)assert.ok(snapshot.files.some(f=>f.path.includes('/'+family+'/')),family);for(const family of families)fs.rmSync(path.join(store.base,family),{recursive:true,force:true});restoreSnapshot(root,snapshot);const readback=new FileWorkspace(root).load();assert.equal(readback.crm.feedbackLinks[0].feedbackId,feedback.id);assert.equal(new ContentService(store).get(item.id).status,'published');assert.equal(new PublicationService(store,()=>({publisher:mock.publisher,secrets:{apiKey:null,maxCreditsPerPost:0,maxCreditsPerDay:0}})).listAttempts()[0].id,attempt.id);assert.ok(readback.deliveryPrograms.length);assert.ok(readback.tasks.some((t:any)=>t.id===legacy.id&&t.stage==='seo-geo'));assert.deepEqual(fs.readFileSync(path.join(store.base,'artifacts','legacy.bin')),Buffer.from([0,255,13,10]));assert.equal(fs.readFileSync(path.join(store.base,'artifacts',legacy.id+'.md'),'utf8'),'# Legacy markdown retained');assert.equal(MODULES.length,13);assert.equal(MODULES.flatMap(m=>m.stages).length,15);
}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('missing budget makes zero paid calls; timeout remains unknown and cannot resend across reload',async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'module-safety-'));try{const store=new FileWorkspace(root),content=new ContentService(store),item=content.create({title:'Fixture',text:'Fixture',channelIds:['fixture-channel'],remoteMediaIds:['fixture-media']});content.approve(item.id,item.contentHash);const mock=mockPublisher(true);let budget=0;const current=()=>({publisher:mock.publisher,secrets:{apiKey:'fixture-only',maxCreditsPerPost:budget,maxCreditsPerDay:budget}}),service=new PublicationService(store,current);await assert.rejects(()=>service.preparePublish(item.id,{channelIds:item.channelIds,mode:'immediate',plannedAt:null}),/budgets/);assert.deepEqual(mock.counts(),{creates:0,publishes:0});budget=1;const c=await service.preparePublish(item.id,{channelIds:item.channelIds,mode:'immediate',plannedAt:null}),attempt=await service.submitPublish(item.id,c.id);assert.equal(attempt.status,'unknown');assert.notEqual(content.get(item.id).status,'published');assert.equal(attempt.actualCredits,null);await new PublicationService(store,current).submitPublish(item.id,c.id);assert.deepEqual(mock.counts(),{creates:1,publishes:1});}finally{fs.rmSync(root,{recursive:true,force:true});}});
