import {test} from 'node:test';
import assert from 'node:assert/strict';
import {MODULES,moduleForStage,artifactsForModule} from '../src/navigation/modules.ts';
const web=await import(new URL('../web/modules.js',import.meta.url).href);
const {route}=await import(new URL('../web/main.js',import.meta.url).href);
const {resultsView}=await import(new URL('../web/views/results.js',import.meta.url).href);
test('13 modules, aliases and four free modules share one mapping',()=>{assert.equal(MODULES.length,13);assert.deepEqual(web.MODULES,MODULES);assert.equal(moduleForStage('seo'),'seo-geo');assert.equal(moduleForStage('geo'),'seo-geo');assert.deepEqual(MODULES.filter(m=>m.free).map(m=>m.id),['market-research','product-opportunity','buyer-check','sales-feedback']);assert.equal(route('#/seo'),'seo-geo/seo');assert.equal(route('#/geo'),'seo-geo/geo');assert.equal(route('#/experts'),'skills');assert.equal(route('#/artifacts'),'artifacts');});
test('project results use real task stages and preserve historical bytes',()=>{const state={tasks:[{id:'t',stage:'seo'},{id:'u',stage:'google-ads'}],artifacts:[{id:'a',taskId:'t',module:'wrong',summary:'SEO evidence'},{id:'b',taskId:'u',module:'seo',summary:'Ads evidence'}],taskRuns:[{id:'r',taskId:'t'}]};const before=JSON.stringify(state);assert.deepEqual(artifactsForModule(state,'seo-geo').map(a=>a.id),['a']);const html=resultsView({state,moduleId:'seo-geo',heading:()=>'',button:()=>'',esc:String});assert.ok(html.includes('SEO evidence'));assert.ok(!html.includes('Ads evidence'));assert.equal(JSON.stringify(state),before);});

import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {FileWorkspace} from '../server.ts';
test('schedule chooser retains real SEO and GEO skill stages',()=>{const source=fs.readFileSync(new URL('../app-v03.js',import.meta.url),'utf8');assert.match(source,/scheduleStages\.map/);assert.match(source,/const scheduleStages=MODULES\.flatMap/);const root=fs.mkdtempSync(path.join(os.tmpdir(),'schedule-alias-'));try{const store=new FileWorkspace(root);for(const stage of ['seo','geo'])store.save({revision:store.load().revision,action:'schedule-create',payload:{name:stage+' schedule',stage}});for(const stage of ['seo','geo']){const s=store.load().schedules.find((s:any)=>s.stage===stage);assert.ok(s);assert.equal(s.skillId,'yundian-growth-'+stage);}}finally{fs.rmSync(root,{recursive:true,force:true});}});
