import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {FileWorkspace} from '../server.ts';
import {ContentService,hashContent} from '../src/content/service.ts';
import {PublicationService} from '../src/publishing/service.ts';
import {validatePublishingRecord} from '../src/publishing/validation.ts';
function fixture(platform='facebook',media:any[]=[]){const root=fs.mkdtempSync(path.join(os.tmpdir(),'final-fix-')),store=new FileWorkspace(root),content=new ContentService(store);let creates=0,publishes=0;const port:any={listChannels:async()=>[{id:'a',platform,name:'A',isActive:true}],listMedia:async()=>media,getBalance:async()=>({balance:100}),createPost:async(input:any)=>{creates++;return {id:'p',status:'draft',scheduledAt:null,postChannels:[]};},publishPost:async(postId:string)=>{publishes++;return {postId,results:[{channelId:'a',status:'published'}]};},getPost:async()=>{throw Error('unknown');}};const current=()=>({publisher:port,secrets:{apiKey:'mock',maxCreditsPerPost:10,maxCreditsPerDay:100}});return {root,store,content,port,current,service:new PublicationService(store,current),effects:()=>creates+publishes};}
test('immutable approved version and submitted payload survive edit and restart',async()=>{const f=fixture();try{let item=f.content.create({title:'ORIGINAL TITLE',text:'ORIGINAL BODY',assetRefs:['original.png'],channelIds:['a']});item=f.content.approve(item.id,item.contentHash);const c=await f.service.preparePublish(item.id,{channelIds:['a'],mode:'immediate',plannedAt:null});const a:any=await f.service.submitPublish(item.id,c.id);f.content.update(item.id,{title:'NEW TITLE',text:'NEW BODY'},f.content.get(item.id).contentRevision);const restarted:any=new PublicationService(f.store,f.current).listAttempts()[0];assert.equal(restarted.approvedContent.title,'ORIGINAL TITLE');assert.equal(restarted.approvedContent.text,'ORIGINAL BODY');assert.equal(hashContent(restarted.approvedContent),a.contentHash);assert.equal(restarted.submittedPayload.content,'ORIGINAL BODY');assert.deepEqual(restarted.approvedContent.assetRefs,['original.png']);assert.throws(()=>validatePublishingRecord({...restarted,approvedContent:{...restarted.approvedContent,text:'tampered'}},item.workspaceId,'publish-attempts'));}finally{fs.rmSync(f.root,{recursive:true,force:true});}});
for(const platform of ['instagram','pinterest','tiktok'])test(platform+' server blocks missing required remote media before effects',async()=>{const media=platform==='tiktok'?[{id:'image',mimeType:'image/png',url:'https://example.com/image'}]:[],f=fixture(platform,media);try{let item=f.content.create({title:'test',assetRefs:['local.png'],remoteMediaIds:media.map(m=>m.id),channelIds:['a']});item=f.content.approve(item.id,item.contentHash);await assert.rejects(()=>f.service.preparePublish(item.id,{channelIds:['a'],mode:'immediate',plannedAt:null}),/Media|video/);assert.equal(f.effects(),0);}finally{fs.rmSync(f.root,{recursive:true,force:true});}});
import {createSnapshot,restoreSnapshot} from '../src/backup/service.ts';
// @ts-ignore browser ES module has no declaration
import {publishReceipt} from '../web/views/content-plan.js';
test('snapshot restore retains immutable receipt and in-flight edits never replace submitted body',async()=>{const f=fixture();try{let item=f.content.create({title:'CAPTURED TITLE',text:'CAPTURED BODY',remoteMediaIds:['m'],channelIds:['a']});item=f.content.approve(item.id,item.contentHash);f.port.listMedia=async()=>[{id:'m',mimeType:'image/png',url:'https://example.com/m'}];let release:any,entered:any;const gate=new Promise<void>(r=>release=r),start=new Promise<void>(r=>entered=r);let sent:any;f.port.createPost=async(input:any)=>{sent=input;entered();await gate;return {id:'p',status:'draft',scheduledAt:null,postChannels:[]};};const c=await f.service.preparePublish(item.id,{channelIds:['a'],mode:'immediate',plannedAt:null});const pending=f.service.submitPublish(item.id,c.id);await start;const before:any=f.service.listAttempts()[0];assert.equal(before.submittedPayload.content,'CAPTURED BODY');f.content.update(item.id,{title:'EDITED TITLE',text:'EDITED BODY',remoteMediaIds:[]},f.content.get(item.id).contentRevision);release();const a:any=await pending;assert.equal(sent.content,'CAPTURED BODY');assert.deepEqual(sent.mediaIds,['m']);assert.equal(a.status,'unknown');assert.equal(f.effects(),0);const snap=createSnapshot(f.root);restoreSnapshot(f.root,snap);const restored:any=new PublicationService(f.store,f.current).listAttempts()[0];assert.equal(restored.approvedContent.title,'CAPTURED TITLE');assert.equal(restored.submittedPayload.content,'CAPTURED BODY');const html=publishReceipt(restored);assert.match(html,/CAPTURED TITLE/);assert.match(html,/CAPTURED BODY/);assert.doesNotMatch(html,/EDITED TITLE/);assert.equal((await f.service.submitPublish(item.id,c.id)).id,a.id);}finally{fs.rmSync(f.root,{recursive:true,force:true});}});
test('submit rereads media metadata and blocks removed video before effects; valid video publishes',async()=>{for(const platform of ['instagram','pinterest','tiktok']){const f=fixture(platform,[{id:'m',mimeType:'video/mp4',url:'https://example.com/m'}]);try{let item=f.content.create({title:'valid',channelIds:['a'],remoteMediaIds:['m']});item=f.content.approve(item.id,item.contentHash);const c=await f.service.preparePublish(item.id,{channelIds:['a'],mode:'immediate',plannedAt:null});f.port.listMedia=async()=>platform==='tiktok'?[{id:'m',mimeType:'image/png',url:'https://example.com/m'}]:[];await assert.rejects(()=>f.service.submitPublish(item.id,c.id),/Media|video/);assert.equal(f.effects(),0);f.port.listMedia=async()=>[{id:'m',mimeType:'video/mp4',url:'https://example.com/m'}];assert.equal((await f.service.submitPublish(item.id,c.id)).status,'published');assert.equal(f.effects(),2);}finally{fs.rmSync(f.root,{recursive:true,force:true});}}});
