import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {FileWorkspace} from '../server.ts';
function fixture(run:(s:FileWorkspace)=>void){const r=fs.mkdtempSync(path.join(os.tmpdir(),'task4-'));try{run(new FileWorkspace(r));}finally{fs.rmSync(r,{recursive:true,force:true});}}
function setup(s:FileWorkspace){s.save({revision:s.load().revision,action:'profile',payload:{company:'test',goal:'research'}});return s.createTask({stage:'market-research',name:'Research'},s.load().revision);}
test('copy is read only; new runs have distinct ids and snapshots',()=>fixture(s=>{const a=setup(s);const before=s.load().revision;assert.equal(s.load().tasks[0].status,'ready');assert.equal(s.load().revision,before);const b=s.createTask({stage:'market-research',name:'Research'},before);assert.notEqual(a.id,b.id);assert.notEqual(a.inputSnapshotRef,b.inputSnapshotRef);}));
test('receipts reject invalid tasks, versions, missing and escaping files without writes',()=>fixture(s=>{const t=setup(s);const file=path.join(s.root,'result.txt');fs.writeFileSync(file,'real');const base={receiptId:'r1',taskId:t.id,workspaceId:t.workspaceId,skillVersion:t.skillVersion,executor:'WorkBuddy',status:'needs-review',artifacts:[{path:file,summary:'report'}]};for(const bad of [{taskId:'bad'},{workspaceId:'other'},{skillVersion:'bad'},{artifacts:[{path:'missing.txt'}]},{artifacts:[{path:'../outside.txt'}]}]){const revision=s.load().revision;assert.throws(()=>s.applyReceipt(t.id,{...base,...bad},revision));assert.equal(s.load().revision,revision);}}));
test('receipts are idempotent, conflicts rejected; reviews become invalid on file changes',()=>fixture(s=>{const t=setup(s);const file=path.join(s.root,'report.txt');fs.writeFileSync(file,'v1');const r={receiptId:'r1',taskId:t.id,workspaceId:t.workspaceId,skillVersion:t.skillVersion,executor:'WorkBuddy',status:'needs-review',artifacts:[{path:file,summary:'report'}]};s.applyReceipt(t.id,r,s.load().revision);const rev=s.load().revision;s.applyReceipt(t.id,r,rev);assert.equal(s.load().revision,rev);assert.equal(s.load().artifacts.length,1);assert.throws(()=>s.applyReceipt(t.id,{...r,executor:'other'},rev),/receipt/);const a=s.load().artifacts[0];s.reviewArtifact(t.id,a.contentHash,'accepted','actual evidence',s.load().revision);assert.equal(s.load().tasks[0].status,'completed');fs.writeFileSync(file,'v2');assert.equal(s.load().tasks[0].status,'needs-review');assert.equal(s.load().reviews[0].valid,false);}));
test('manual uploads and links remain unverified and cannot imply execution',()=>fixture(s=>{const t=setup(s);s.save({action:'artifact',payload:{id:t.id,content:'uploaded'},revision:s.load().revision});assert.equal(s.load().artifacts[0].verification,'unverified');assert.equal(s.load().artifacts[0].executedAt,null);s.applyReceipt(t.id,{receiptId:'url1',taskId:t.id,workspaceId:t.workspaceId,skillVersion:t.skillVersion,executor:'WorkBuddy',status:'needs-review',artifacts:[{url:'https://example.com',summary:'link'}]},s.load().revision);const a=s.load().artifacts.find((a:any)=>a.url);assert.equal(a.verification,'unverified');assert.throws(()=>s.reviewArtifact(t.id,a.contentHash,'accepted','evidence',s.load().revision));}));
test('knowledge confirmation requires exact current hash; edits invalidate confirmation',()=>fixture(s=>{setup(s);s.save({action:'knowledge',payload:{title:'Fact',content:'fact',source:'customer'},revision:s.load().revision});const k=s.load().knowledge.find((k:any)=>k.path.includes('profile')===false&&k.path.includes('index')===false&&k.content.includes('fact'));s.confirmKnowledge(k.path,k.contentHash,s.load().revision);assert.equal(s.load().knowledge.find((v:any)=>v.path===k.path).reviewStatus,'confirmed');fs.appendFileSync(path.join(s.base,k.path),'change');assert.equal(s.load().knowledge.find((v:any)=>v.path===k.path).reviewStatus,'pending');}));

test('multiple files preflight, restart persistence, and manual links have no execution time',()=>fixture(s=>{const t=setup(s);fs.writeFileSync(path.join(s.root,'one.txt'),'one');const receipt={receiptId:'multi',taskId:t.id,workspaceId:t.workspaceId,skillVersion:t.skillVersion,executor:'WorkBuddy',status:'needs-review',artifacts:[{path:'one.txt'},{path:'two.txt'}]};const rev=s.load().revision;assert.throws(()=>s.applyReceipt(t.id,receipt,rev));assert.equal(s.load().revision,rev);assert.equal(s.load().artifacts.length,0);fs.writeFileSync(path.join(s.root,'two.txt'),'two');s.applyReceipt(t.id,receipt,s.load().revision);const restart=new FileWorkspace(s.root);assert.equal(restart.load().artifacts.length,2);const a=restart.load().artifacts[0];assert.throws(()=>restart.reviewArtifact(t.id,'0'.repeat(64),'accepted','checked',restart.load().revision));restart.reviewArtifact(t.id,a.contentHash,'accepted','checked',restart.load().revision);assert.equal(restart.load().tasks[0].status,'needs-review');restart.applyReceipt(t.id,{...receipt,receiptId:'manual',executor:'manual',artifacts:[{url:'https://example.com'}]},restart.load().revision);assert.equal(restart.load().artifacts.find((a:any)=>a.url).executedAt,null);}));
test('identical-content artifacts review the explicitly selected artifact',()=>fixture(s=>{const t=setup(s);fs.writeFileSync(path.join(s.root,'same.txt'),'same');for(const receiptId of ['one','two'])s.applyReceipt(t.id,{receiptId,taskId:t.id,workspaceId:t.workspaceId,skillVersion:t.skillVersion,executor:'WorkBuddy',status:'needs-review',artifacts:[{path:'same.txt'}]},s.load().revision);const a=s.load().artifacts[1];s.save({action:'review',payload:{id:t.id,artifactId:a.id,contentHash:a.contentHash,review:'selected'},revision:s.load().revision});assert.equal(s.load().reviews[0].artifactId,a.id);}));
test('latest rejection overrides previous acceptance for unchanged content',()=>fixture(s=>{const t=setup(s);s.save({action:'artifact',payload:{id:t.id,content:'real'},revision:s.load().revision});const a=s.load().artifacts[0];s.reviewArtifact(t.id,a.contentHash,'accepted','initial check',s.load().revision,a.id);assert.equal(s.load().tasks[0].status,'completed');s.reviewArtifact(t.id,a.contentHash,'rejected','recheck needs correction',s.load().revision,a.id);assert.equal(s.load().tasks[0].status,'needs-review');}));
test('receipt metadata rejects non-string arrays before every write',()=>fixture(s=>{const t=setup(s);fs.writeFileSync(path.join(s.root,'metadata.txt'),'actual');for(const key of ['sources','gaps','nextSteps'])for(const value of ['invalid',null,{invalid:true},['valid',42]]){const revision=s.load().revision;const receipt={receiptId:'metadata-'+key,taskId:t.id,workspaceId:t.workspaceId,skillVersion:t.skillVersion,executor:'WorkBuddy',status:'needs-review',artifacts:[{path:'metadata.txt'},{path:'metadata.txt',[key]:value}]};assert.throws(()=>s.applyReceipt(t.id,receipt,revision),new RegExp(key));assert.equal(s.load().revision,revision);assert.equal(s.load().artifacts.length,0);assert.equal(s.files('receipts','.json').length,0);assert.equal(s.task(t.id).status,'ready');}const receipt={receiptId:'valid-metadata',taskId:t.id,workspaceId:t.workspaceId,skillVersion:t.skillVersion,executor:'WorkBuddy',status:'needs-review',artifacts:[{path:'metadata.txt',sources:['customer'],gaps:[],nextSteps:['review']}]};s.applyReceipt(t.id,receipt,s.load().revision);assert.deepEqual(s.load().artifacts[0].sources,['customer']);}));
test('results view preserves usable controls for malformed historical metadata',async()=>{const {resultsView}=await import(new URL('../web/views/results.js',import.meta.url).href);const state={tasks:[],reviews:[],artifacts:[{id:'artifact',taskId:'task',path:'file.txt',contentHash:'hash',sources:'legacy source',gaps:{malformed:true},nextSteps:['valid next',{malformed:true}]}]};const html=resultsView({state,heading:()=>'',button:(text:string,action:string)=>`<button data-action="${action}">${text}</button>`,esc:(text:unknown)=>String(text??'')});assert.ok(html.includes('legacy source'));assert.ok(html.includes('valid next'));for(const action of ['view-result','review-result','rerun'])assert.ok(html.includes(`data-action="${action}"`));assert.ok(html.includes('/api/artifacts/artifact/file'));});
