import crypto from 'node:crypto';
import type {Schedule} from '../domain/contracts.ts';
import type {HostReceipt,ScheduleInput} from './adapter.ts';
export interface ManagedSchedule extends Schedule {name:string;stage:string;time:string;operation:string;command:string;pauseRequested:boolean;receiptVerified:boolean;hostReceipt?:HostReceipt;error?:string;createdAt:string}
const operations=['draft','plan','report','analysis','send','publish','ads','budget'];
const hash=(s:string)=>crypto.createHash('sha256').update(s).digest('hex');
function zoneCheck(zone:string){new Intl.DateTimeFormat('en-US',{timeZone:zone}).format();}
function dateCheck(date:string){if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||new Date(date+'T00:00:00Z').toISOString().slice(0,10)!==date)throw Error('日期无效');}
function timeCheck(time:string){if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(time))throw Error('时间必须为 HH:mm');}
function wall(instant:number,zone:string){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date(instant));const p=Object.fromEntries(parts.map(x=>[x.type,x.value]));return `${p.year}-${p.month}-${p.day}T${p.hour}:${p.minute}`;}
// Match offsets around the target date, then select the earliest real instant for ambiguous wall times.
export function localOccurrence(date:string,time:string,zone:string):string|null{dateCheck(date);timeCheck(time);zoneCheck(zone);const base=Date.parse(date+'T'+time+':00Z'),target=date+'T'+time;const offsets=new Set<number>();for(let h=-48;h<=48;h+=6){const t=base+h*3600000;offsets.add(Date.parse(wall(t,zone)+':00Z')-t);}const matches=[...offsets].map(offset=>base-offset).filter(t=>wall(t,zone)===target).sort((a,b)=>a-b);return matches.length?new Date(matches[0]).toISOString():null;}
export function occurrenceKey(scheduleId:string,scheduledAt:string){if(!/(Z|[+-]\d\d:\d\d)$/.test(scheduledAt)||!Number.isFinite(Date.parse(scheduledAt)))throw Error('计划时点需要带时区的 ISO 时间');return hash(scheduleId+'\n'+new Date(scheduledAt).toISOString());}
export function creationCommand(s:ManagedSchedule){return `请在当前客户 WorkBuddy 项目用原生定时能力创建任务（能力不支持则说明，不模拟创建）。\n客户空间：${s.workspaceId}\n计划编号：${s.id}\n任务：${s.name}\n技能：${s.skillId}\n频率：每日 ${s.time}，时区 ${s.timezone}\n输入：${JSON.stringify(s.inputs)}\n输出目录：${s.outputPath}\n操作范围：${s.operation}；授权：${JSON.stringify(s.authorization)}\n每个计划时点只执行一次；不存在的夏令时时点跳过，重复时点选择第一次。先登记 schedule-occurrence 获取真实执行任务及指令，按任务回执路径返回实际结果。外部发送/发布/广告/预算须核验明确授权，失败不得自动重试。\n创建后提供原生任务编号、可核验创建回执、来源。网页关闭不影响已由宿主创建的任务；宿主未运行或能力不支持不能保证执行。`}
export function createSchedule(input:ScheduleInput):ManagedSchedule{if(!input.workspaceId||!input.skillId||!input.stage||!input.name?.trim())throw Error('请填写计划名称与技能');const timezone=input.timezone||'Asia/Shanghai',time=input.time||'09:00';zoneCheck(timezone);timeCheck(time);if(input.frequency&&input.frequency!=='daily')throw Error('当前仅支持每日频率');const operation=input.operation||'draft';if(!operations.includes(operation))throw Error('操作范围无效');const s:ManagedSchedule={id:crypto.randomUUID().replaceAll('-',''),workspaceId:input.workspaceId,skillId:input.skillId,stage:input.stage,name:input.name.trim(),timezone,time,frequency:'daily',inputs:input.inputs||{},outputPath:input.outputPath||'growth-workspace/artifacts',authorization:input.authorization||{},operation,status:'unsupported',hostTaskId:null,receipt:null,command:'',pauseRequested:false,receiptVerified:false,createdAt:new Date().toISOString()};s.command=creationCommand(s);return s;}
// The verifier must be supplied by a trusted native adapter. Never accept a client supplied verified flag.
export function registerHostReceipt(s:ManagedSchedule,r:HostReceipt,verify:(receipt:HostReceipt,schedule:ManagedSchedule)=>boolean=()=>false):ManagedSchedule{if(r.workspaceId!==s.workspaceId||r.scheduleId!==s.id)throw Error('宿主回执客户或计划不匹配');if(!['create','pause'].includes(r.action)||!['enabled','paused','failed','unsupported','pending-host'].includes(r.status))throw Error('回执状态无效');if(!r.source?.trim()||!r.evidence?.trim())throw Error('请提供回执来源和证据');if(r.action==='pause'&&(!s.pauseRequested||r.hostTaskId!==s.hostTaskId))throw Error('暂停回执不匹配');if(r.action==='create'&&s.pauseRequested)throw Error('计划正在等待暂停，不能登记创建回执');const verified=verify(r,s);if(verified&&((r.status==='enabled'&&r.action!=='create')||(r.status==='paused'&&r.action!=='pause')))throw Error('回执动作与状态不匹配');if(verified&&['enabled','paused'].includes(r.status)&&!r.hostTaskId?.trim())throw Error('缺少真实宿主任务编号');return {...s,hostReceipt:r,hostTaskId:r.hostTaskId||s.hostTaskId,receipt:JSON.stringify(r),receiptVerified:verified,status:verified?r.status==='pending-host'?'pending-host':r.status:'pending-host',error:r.error||'',pauseRequested:s.pauseRequested};}
export function requestPause(s:ManagedSchedule):ManagedSchedule{return {...s,status:'pending-host',pauseRequested:true,receiptVerified:false};}
export function authorizationAllowed(s:ManagedSchedule){return ['draft','plan','report','analysis'].includes(s.operation)||(s.authorization.approved===true&&s.authorization.operation===s.operation&&typeof s.authorization.scope==='string'&&!!s.authorization.scope.trim()&&typeof s.authorization.evidence==='string'&&!!s.authorization.evidence.trim());}
export function validateOccurrence(s:ManagedSchedule,scheduledAt:string){if(s.status!=='enabled'||!s.receiptVerified||s.pauseRequested)throw Error('宿主未核验启用或正在等待暂停');occurrenceKey(s.id,scheduledAt);const instant=Date.parse(scheduledAt),date=wall(instant,s.timezone).slice(0,10),canonical=localOccurrence(date,s.time,s.timezone);if(canonical!==new Date(instant).toISOString())throw Error('不是本计划时点，或为重复夏令时时点');return canonical;}
