import crypto from 'node:crypto';
import path from 'node:path';
import fs from 'node:fs';
import {WorkspaceStore} from '../storage/workspace-store.ts';
import {crmFamilies,stages,validId,normalize,validateCrmDataset} from './validation.ts';
import type {DatasetRow} from './validation.ts';
import type {CompanyInput,ContactInput,LeadInput,LeadPatch,FollowUpInput,CrmCompany,CrmContact,CrmLead,CrmFollowUp,CrmFilter,CrmImportPreview,CrmImportDecision,FeedbackLink,CrmLeadContext} from './contracts.ts';
const id=()=>crypto.randomUUID().replaceAll('-','');
const now=()=>new Date().toISOString();
const truth=(v:unknown)=>v===true||v==='true';
const name=(v:string)=>v.trim().toLowerCase().replace(/\s+/g,' ');
const domain=(v:string)=>v?new URL(v).hostname.toLowerCase().replace(/^www\./,''):'';
export class CrmService {
 store:WorkspaceStore;workspaceId:string;previews=new Map<string,{preview:CrmImportPreview;digest:string}>();
 constructor(store:WorkspaceStore){this.store=store;this.workspaceId=store.json(path.join(store.base,'workspace.json')).workspaceId;}
 dataset():DatasetRow[]{const rows=[...crmFamilies,'tasks','artifacts','feedback','records'].flatMap(family=>this.store.files(family,'.json').map(file=>({family,filename:path.basename(file),value:this.store.json(file)})));validateCrmDataset(rows,this.workspaceId);return rows;}
 fingerprint(){const digest=(this.store as WorkspaceStore & {digest?:()=>string}).digest;if(digest)return digest.call(this.store);return crypto.createHash('sha256').update(JSON.stringify(this.dataset())).digest('hex');}
 list(family:string,filter:CrmFilter={}):any[]{if(filter.stage&&!stages.includes(filter.stage))throw Error('Invalid stage');if(filter.companyId&&!validId(filter.companyId)||filter.leadId&&!validId(filter.leadId))throw Error('Invalid filter');const all=this.dataset();const dueIds=new Set<string>();if(family==='crm-followups'&&truth(filter.overdue)){for(const {value:lead} of all.filter(r=>r.family==='crm-leads')){const company=all.find(r=>r.family==='crm-companies'&&r.value.id===lead.companyId)?.value;if(lead.archivedAt||company?.archivedAt||['won','lost'].includes(lead.stage))continue;const latest=all.filter(r=>r.family==='crm-followups'&&r.value.leadId===lead.id&&r.value.kind==='followup'&&!r.value.archivedAt).map(r=>r.value).sort((a,b)=>b.time.localeCompare(a.time)||b.createdAt.localeCompare(a.createdAt)||b.id.localeCompare(a.id))[0];if(latest?.nextFollowUpAt&&latest.nextFollowUpAt<=now())dueIds.add(latest.id);}}return all.filter(r=>r.family===family).map(r=>r.value).filter(v=>
  (truth(filter.includeArchived)||!v.archivedAt)&&(!filter.query||JSON.stringify(v).toLowerCase().includes(filter.query.toLowerCase()))&&(!filter.owner||v.owner===filter.owner)&&(!filter.stage||v.stage===filter.stage)&&(!filter.companyId||v.companyId===filter.companyId)&&(!filter.leadId||v.leadId===filter.leadId)&&(!filter.country||(v.country??all.find(r=>r.family==='crm-companies'&&r.value.id===v.companyId)?.value.country)===filter.country)&&(!truth(filter.overdue)||family==='crm-followups'&&dueIds.has(v.id)));}
 listCompanies(f:CrmFilter={}):CrmCompany[]{return this.list('crm-companies',f);}
 listContacts(f:CrmFilter={}):CrmContact[]{return this.list('crm-contacts',f);}
 listLeads(f:CrmFilter={}):CrmLead[]{return this.list('crm-leads',f);}
 listFollowUps(f:CrmFilter={}):CrmFollowUp[]{return this.list('crm-followups',f);}
 get(family:string,entityId:string):any{if(!validId(entityId))throw Error('Invalid CRM ID');const v=this.dataset().find(r=>r.family===family&&r.value.id===entityId)?.value;if(!v)throw Error('CRM record not found');return v;}
 crmLeadContext(entityId:string):CrmLeadContext{const lead=this.get('crm-leads',entityId) as CrmLead,company=this.get('crm-companies',lead.companyId) as CrmCompany;const contacts=lead.contactIds.map(id=>this.get('crm-contacts',id) as CrmContact),followups=this.listFollowUps({leadId:entityId,includeArchived:true});const tasks=this.dataset().filter(r=>r.family==='tasks'&&r.value.sourceLeadId===lead.id).map(r=>r.value);const artifactIds=[...new Set([...followups.flatMap(f=>f.artifactIds),...tasks.flatMap(t=>t.artifactIds||[])])];return {lead,company,contacts,followups,artifactIds,tasks};}
 linkFeedback(feedbackId:string,crmLeadId:string):FeedbackLink{this.active('crm-leads',crmLeadId);const rows=this.dataset();if(!rows.some(r=>r.family==='feedback'&&r.value.id===feedbackId))throw Error('Feedback not found');const old=rows.find(r=>r.family==='crm-feedback-links'&&r.value.feedbackId===feedbackId);if(old){if(old.value.crmLeadId!==crmLeadId)throw Error('Feedback already linked to another lead');return old.value;}const value={id:id(),workspaceId:this.workspaceId,feedbackId,crmLeadId,confirmedAt:now()};this.commit([this.row('crm-feedback-links',value)]);return value;}
 input(family:string,value:any):any {const normalized=normalize(family,value);for(const key of Object.keys(value))if(!Object.hasOwn(normalized,key))throw Error('Unsupported or server-owned field '+key);return normalized;}
 base(){const time=now();return {id:id(),workspaceId:this.workspaceId,createdAt:time,updatedAt:time,archivedAt:null};}
 commit(jobs:DatasetRow[]):void {const rows=this.dataset();const merged=new Map(rows.map(r=>[r.family+'/'+r.filename,r]));for(const row of jobs)merged.set(row.family+'/'+row.filename,row);validateCrmDataset([...merged.values()],this.workspaceId);
  const originals=new Map<string,Buffer|null>();try{for(const row of jobs){const file=this.store.checked(path.join(this.store.base,row.family,row.filename));originals.set(file,fs.existsSync(file)?fs.readFileSync(file):null);this.store.put(file,row.value);}}catch(e){for(const [file,bytes] of originals){if(bytes===null){if(fs.existsSync(file))fs.unlinkSync(file);}else this.store.write(file,bytes.toString('utf8'));}throw e;}}
 row(family:string,value:any):DatasetRow{return {family,filename:value.id+'.json',value};}
 createCompany(input:CompanyInput):CrmCompany{const value={...this.input('crm-companies',input),...this.base()};this.commit([this.row('crm-companies',value)]);return value;}
 createContact(input:ContactInput):CrmContact{const value={...this.input('crm-contacts',input),...this.base()};this.active('crm-companies',value.companyId);this.commit([this.row('crm-contacts',value)]);return value;}
 active(family:string,entityId:string){const v=this.get(family,entityId);if(v.archivedAt)throw Error('CRM parent archived');return v;}
 updateCompany(entityId:string,input:Partial<CompanyInput>):CrmCompany{return this.update('crm-companies',entityId,input);}
 updateContact(entityId:string,input:Partial<ContactInput>):CrmContact{const old=this.get('crm-contacts',entityId);if(Object.hasOwn(input,'companyId')&&input.companyId!==old.companyId)throw Error('Create a sourced contact for a new company relationship');return this.update('crm-contacts',entityId,input);}
 update(family:string,entityId:string,input:any):any {if(!input||typeof input!=='object'||Array.isArray(input))throw Error('Missing structured CRM patch');const old=this.get(family,entityId);this.input(family,{...normalize(family,old),...input});const value={...old,...input,updatedAt:now()};this.commit([this.row(family,value)]);return value;}
 archiveEntity(kind:'company'|'contact'|'lead',entityId:string):void {const family=kind==='company'?'crm-companies':kind==='contact'?'crm-contacts':kind==='lead'?'crm-leads':'';if(!family)throw Error('Invalid archive kind');const value=this.get(family,entityId);this.commit([this.row(family,{...value,archivedAt:now(),updatedAt:now()})]);}
 createLead(input:LeadInput):CrmLead{const n=this.input('crm-leads',input);this.active('crm-companies',n.companyId);for(const contactId of n.contactIds){const c=this.active('crm-contacts',contactId);if(c.companyId!==n.companyId)throw Error('Contact belongs to another company');}const value={...n,...this.base(),stage:'new',sourceLinks:[]};this.commit([this.row('crm-leads',value)]);return value;}
 updateLead(entityId:string,patch:LeadPatch):CrmLead {if(!patch||typeof patch!=='object'||Array.isArray(patch)||Object.keys(patch).some(k=>!['stage','owner','tags','productInterests'].includes(k)))throw Error('Invalid lead patch');const old=this.get('crm-leads',entityId);const value={...old,...patch,updatedAt:now()};const jobs=[this.row('crm-leads',value)];if(patch.stage&&patch.stage!==old.stage){const event={...normalize('crm-followups',{leadId:entityId,time:now(),method:'stage-change',content:'Customer changed stage: '+old.stage+' → '+patch.stage}),...this.base(),kind:'stage-change',fromStage:old.stage,toStage:patch.stage};jobs.push(this.row('crm-followups',event));}this.commit(jobs);return value;}
 recordFollowUp(input:FollowUpInput):CrmFollowUp{const n=this.input('crm-followups',input);this.active('crm-leads',n.leadId);const value={...n,...this.base(),kind:'followup',fromStage:null,toStage:null};this.commit([this.row('crm-followups',value)]);return value;}
 previewImport(rows:unknown[]):CrmImportPreview {if(!Array.isArray(rows)||rows.length>1000)throw Error('Invalid import rows');const preview:CrmImportPreview={id:id(),workspaceId:this.workspaceId,schemaVersion:1,candidates:[],errors:[],duplicates:[]};const existing=this.dataset();rows.forEach((raw:any,index)=>{try{
  if(!raw||typeof raw!=='object'||Array.isArray(raw)||raw.schemaVersion!==1||raw.workspaceId!==this.workspaceId||Object.keys(raw).some(k=>!['schemaVersion','workspaceId','company','contacts','lead'].includes(k))||!Array.isArray(raw.contacts))throw Error('Invalid CRM import schema/workspace');
  const company=this.input('crm-companies',raw.company);const temporary=id();
  const contacts=raw.contacts.map((c:any)=>{if(c.companyId!==undefined)throw Error('Import contact parent is supplied by company');return this.input('crm-contacts',{...c,companyId:temporary});});
  if(raw.lead.companyId!==undefined||raw.lead.contactIds!==undefined)throw Error('Import lead parents are supplied by row');
  const lead=this.input('crm-leads',{...raw.lead,companyId:temporary});const candidate={candidateId:id(),company,contacts,lead};const stagedCompany={...company,...this.base(),id:temporary};const stagedContacts=contacts.map((v:any)=>({...v,...this.base()}));const stagedLead={...lead,...this.base(),contactIds:stagedContacts.map((v:any)=>v.id),stage:'new',sourceLinks:[]};validateCrmDataset([...existing,this.row('crm-companies',stagedCompany),...stagedContacts.map((v:any)=>this.row('crm-contacts',v)),this.row('crm-leads',stagedLead)],this.workspaceId);preview.candidates.push(candidate);
  for(const {family,value:l} of existing.filter(r=>r.family==='crm-leads')){void family;const c=existing.find(r=>r.family==='crm-companies'&&r.value.id===l.companyId)!.value;const sameCompany=name(c.name)===name(company.name)||!!company.website&&domain(c.website)===domain(company.website);const emails=contacts.map((c:any)=>name(c.email)).filter(Boolean);const sameEmail=existing.some(r=>r.family==='crm-contacts'&&l.contactIds.includes(r.value.id)&&emails.includes(name(r.value.email)));if(sameCompany||sameEmail||lead.sourceLeadId&&l.source===lead.source&&l.sourceLeadId===lead.sourceLeadId)preview.duplicates.push({candidateId:candidate.candidateId,existingLeadId:l.id});}
  // Companies and contacts are independent records; a match never requires or creates a lead.
  for(const {value:matched} of existing.filter(r=>r.family==='crm-companies'))if(name(matched.name)===name(company.name)||!!company.website&&domain(matched.website)===domain(company.website))preview.duplicates.push({candidateId:candidate.candidateId,existingCompanyId:matched.id});
  const candidateEmails=contacts.map((contact:any)=>name(contact.email)).filter(Boolean);
  for(const {value:matched} of existing.filter(r=>r.family==='crm-contacts'))if(matched.email&&candidateEmails.includes(name(matched.email)))preview.duplicates.push({candidateId:candidate.candidateId,existingCompanyId:matched.companyId,existingContactId:matched.id});
 }catch(e:any){preview.errors.push({row:index+1,message:e.message});}});this.previews.set(preview.id,{preview:structuredClone(preview),digest:this.fingerprint()});return preview;}
 confirmImport(previewId:string,decisions:CrmImportDecision[]):CrmLead[]{const saved=this.previews.get(previewId);if(!saved||saved.preview.errors.length)throw Error('Import preview has errors or is unavailable');if(saved.digest!==this.fingerprint())throw Error('CRM changed since import preview');const p=saved.preview;if(!Array.isArray(decisions)||decisions.length!==p.candidates.length||new Set(decisions.map(d=>d.candidateId)).size!==decisions.length)throw Error('Every import candidate needs one decision');const jobs:DatasetRow[]=[],result:CrmLead[]=[];
  for(const d of decisions){const c=p.candidates.find(c=>c.candidateId===d.candidateId);if(!c||!['create','skip','link-existing'].includes(d.action))throw Error('Invalid import decision');if(d.action==='skip')continue;
   if(d.action==='link-existing'){const old=jobs.find(r=>r.family==='crm-leads'&&r.value.id===d.existingLeadId)?.value??this.active('crm-leads',d.existingLeadId!);const value={...old,updatedAt:now(),sourceLinks:[...old.sourceLinks,{source:c.lead.source,sourceLeadId:c.lead.sourceLeadId??'',confirmedAt:now()}]};jobs.push(this.row('crm-leads',value));result.push(value);continue;}
   const company={...normalize('crm-companies',c.company),...this.base()};jobs.push(this.row('crm-companies',company));const contacts=c.contacts.map(input=>({...normalize('crm-contacts',{...input,companyId:company.id}),...this.base()}));jobs.push(...contacts.map(v=>this.row('crm-contacts',v)));const lead={...normalize('crm-leads',{...c.lead,companyId:company.id,contactIds:contacts.map(v=>v.id)}),...this.base(),stage:'new',sourceLinks:[]};jobs.push(this.row('crm-leads',lead));result.push(lead);
  }
  // Collapse explicit source links for the same existing lead before one validated transaction.
  this.commit([...new Map(jobs.map(r=>[r.family+'/'+r.filename,r])).values()]);this.previews.delete(previewId);return result;}
}
