import {api} from '../api.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function localCalendarDay(item){if(!item.plannedAt)return null;const parts=new Intl.DateTimeFormat('en',{timeZone:item.timezone,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date(item.plannedAt));const value=type=>parts.find(part=>part.type===type).value;return value('year')+'-'+value('month')+'-'+value('day');}
export function contentPlanView(){return '<section class="panel content-plan"><h2>选题与排期</h2><p>结构化计划导入后保存为本客户内容；审核后可进入发布确认。发布须审核当前版本、确认渠道和明确积分预算；素材在发布账号网页上传后关联。</p><div id="content-plan-root">加载内容…</div></section>';}
export async function mountContentPlan(host,{token,revision,onRevision,artifacts=[]}){let attempts=[];let items=[],preview=null,mode='list',filters={},week=new Date().toISOString().slice(0,10);const error=e=>{const el=host.querySelector('[role=alert]');if(el)el.textContent=e.message;};async function post(endpoint,body){const data=await api.request('/api/content/'+endpoint,{method:'POST',headers:{'x-workspace-token':token},body:JSON.stringify({...body,revision})});revision=data.revision;onRevision(revision);items=data.items;if(data.attempts)attempts=data.attempts;return data.result;}
function filtered(){return items.filter(x=>(!filters.productRef||x.productRef.includes(filters.productRef))&&(!filters.channelId||x.channelIds.includes(filters.channelId))&&(!filters.status||x.status===filters.status)&&(!filters.from||x.plannedAt&&localCalendarDay(x)>=filters.from)&&(!filters.to||x.plannedAt&&localCalendarDay(x)<=filters.to));}
function localTime(x){return x.plannedAt?new Date(x.plannedAt).toLocaleString('zh-CN',{timeZone:x.timezone})+' '+x.timezone:'未排期';}
function row(x){const a=artifacts.find(a=>a.taskId===x.sourceTaskId);return `<tr><td>${esc(x.title)}<br><small>${esc(x.language)} · ${esc(x.purpose)}</small></td><td>${esc(x.productRef||'未关联')}</td><td>${esc(x.contentType)}</td><td>${esc(x.channelIds.join(', '))}</td><td>${esc(localTime(x))}</td><td>本地 ${x.assetRefs.length} / 远端 ${x.remoteMediaIds.length}</td><td>${esc(x.reviewStatus)}</td><td>${esc(x.status)}${x.publisherPostId?'<br><small>保留旧远端记录；本地编辑不会取消远端排期</small>':''}</td><td><button data-cp="edit" data-id="${esc(x.id)}">编辑/预览</button><button data-cp="publish" data-id="${esc(x.id)}">发布/回执</button><button data-cp="approve" data-id="${esc(x.id)}">批准</button><button data-cp="archive" data-id="${esc(x.id)}">归档</button>${a?`<button data-action="view-result" data-id="${esc(a.id)}">来源成果</button>`:''}</td></tr>`;}
function render(){const rows=filtered();host.innerHTML=`<div class="actions"><button data-cp="new">新增选题</button><button data-cp="list">列表</button><button data-cp="week">周排期</button><button data-cp="import">导入 JSON/CSV</button><button data-cp="export">导出 content-plan.json</button></div><div class="content-filters">${[['productRef','产品'],['channelId','渠道']].map(([k,l])=>`<label>${l}<input data-filter="${k}" value="${esc(filters[k]||'')}"></label>`).join('')}<label>状态<select data-filter="status"><option value="">全部</option>${['idea','draft','ready','scheduled','publishing','published','partial','failed','unknown'].map(v=>`<option ${filters.status===v?'selected':''}>${v}</option>`).join('')}</select></label><label>开始<input type="date" data-filter="from" value="${esc(filters.from||'')}"></label><label>结束<input type="date" data-filter="to" value="${esc(filters.to||'')}"></label></div><div role="alert" class="error"></div><div id="cp-editor"></div>${mode==='week'?`<label>周起始日期<input type="date" data-week value="${week}"></label><div class="content-week">${Array.from({length:7},(_,i)=>{const day=new Date(week+'T00:00:00Z');day.setUTCDate(day.getUTCDate()+i);const d=day.toISOString().slice(0,10);return `<article><h3>${d}</h3>${rows.filter(x=>x.plannedAt&&localCalendarDay(x)===d).map(x=>`<button data-cp="edit" data-id="${esc(x.id)}">${esc(x.title)}<br>${esc(localTime(x))}</button>`).join('')||'<p>无排期</p>'}</article>`;}).join('')}</div>`:`<div class="content-table"><table><thead><tr>${['选题/标题','关联产品','内容类型','目标渠道','计划时间','素材完成情况','审核状态','发布状态','操作'].map(x=>'<th>'+x+'</th>').join('')}</tr></thead><tbody>${rows.map(row).join('')||'<tr><td colspan="9">暂无内容</td></tr>'}</tbody></table></div>`}`;}
function edit(x){const data=x||{title:'',text:'',timezone:'Asia/Shanghai',contentType:'post',language:'zh-CN'};const area=host.querySelector('#cp-editor');area.innerHTML=`<form data-editor><h3>${x?'编辑/预览':'新增选题'}</h3>${['title','productRef','purpose','contentType','language','cycleId','sourceTaskId','plannedAt','timezone'].map(k=>`<label>${k}<input name="${k}" value="${esc(data[k]||'')}" ${k==='title'?'required':''}></label>`).join('')}<label>正文<textarea name="text">${esc(data.text||'')}</textarea></label>${['keywords','assetRefs','remoteMediaIds','channelIds'].map(k=>`<label>${k}（JSON数组）<input name="${k}" value="${esc(JSON.stringify(data[k]||[]))}"></label>`).join('')}<p>本地路径为素材来源，远端素材 ID 必须来自实际账号。</p><button type="submit">保存内容</button><button type="button" data-cp="cancel">取消</button></form>`;area.querySelector('form').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;try{const input=Object.fromEntries(new FormData(e.target));for(const k of ['keywords','assetRefs','remoteMediaIds','channelIds'])input[k]=JSON.parse(input[k]);input.plannedAt=input.plannedAt||null;input.sourceTaskId=input.sourceTaskId||null;await post(x?'items/'+x.id:'items',{input,expectedRevision:x?.contentRevision});render();}catch(e){error(e);}finally{b.disabled=false;}};}
function importForm(){host.querySelector('#cp-editor').innerHTML='<form data-import><h3>导入结构化计划</h3><p>JSON 必须有 schemaVersion:1、workspaceId、items；CSV数组列为JSON数组。任意报告不会自动解析。</p><select name="format"><option>json</option><option>csv</option></select><textarea name="raw" required placeholder="粘贴 content-plan.json 或 CSV"></textarea><button type="submit">预览导入</button></form>';host.querySelector('[data-import]').onsubmit=async e=>{e.preventDefault();try{preview=await post('import/preview',Object.fromEntries(new FormData(e.target)));host.querySelector('#cp-editor').innerHTML=`<form data-confirm><h3>导入预览</h3>${preview.errors.map(x=>`<p class="error">行 ${x.row}: ${esc(x.message)}</p>`).join('')}${preview.candidates.map(c=>{const conflict=preview.conflicts.find(x=>x.candidateId===c.candidateId);return `<article><strong>${esc(c.input.title)}</strong><pre>${esc(c.input.text)}</pre>${conflict?`<p>现有版本 ${conflict.local.contentRevision}: ${esc(conflict.local.text)}</p><select name="${c.candidateId}"><option value="keep-local">保留客户编辑</option><option value="apply-new">明确应用新版本</option></select>`:`<select name="${c.candidateId}"><option value="create">新增</option><option value="keep-local">跳过</option></select>`}</article>`;}).join('')}<button type="submit" ${preview.candidates.length?'':'disabled'}>确认导入</button></form>`;host.querySelector('[data-confirm]').onsubmit=async e=>{e.preventDefault();try{await post('import/confirm',{previewId:preview.id,decisions:Array.from(new FormData(e.target),([candidateId,action])=>({candidateId,action}))});render();}catch(e){error(e);}};}catch(e){error(e);}};}
async function openPublish(item){
 const area=host.querySelector('#cp-editor');area.innerHTML='<p>读取发布配置、渠道、媒体和余额…</p>';
 let cfg,channels,media,balance;
 try{const durable=await readPublicationState();items=durable.items;attempts=durable.attempts;revision=durable.revision;onRevision(revision);item=items.find(x=>x.id===item.id);if(!item)throw Error('内容已不可用，请核对工作区。');}catch(e){area.innerHTML='<p role="alert">实际内容和回执读取失败：'+esc(e.message)+'；状态尚未核实，请刷新工作区后核对，不要重新提交。</p>';return;}
 try{cfg=await api.request('/api/publisher/config');if(!cfg.configured){area.innerHTML='<p role="alert">发布服务未配置，请在服务器配置密钥。</p>'+attempts.filter(a=>a.itemId===item.id).map(publishReceipt).join('');wireRefresh(area,item);return;}const values=await Promise.all([api.request('/api/publisher/channels'),api.request('/api/publisher/media'),api.request('/api/publisher/balance')]);channels=values[0].channels;media=values[1].media;balance=values[2].balance;}catch(e){area.innerHTML='<p role="alert">'+esc(e.message)+'</p>';return;}
 area.innerHTML=`<form data-publish-form><h3>发布准备：${esc(item.title)}</h3><pre>${esc(item.text)}</pre><p>当前版本 ${esc(item.contentRevision)}；审核 ${esc(item.reviewStatus)}；余额 ${esc(balance)}；单次上限 ${esc(cfg.maxCreditsPerPost)}；每日上限 ${esc(cfg.maxCreditsPerDay)}（Asia/Shanghai）</p><fieldset><legend>当前账号渠道</legend>${channels.map(c=>`<label><input name="channels" type="checkbox" value="${esc(c.id)}" ${item.channelIds.includes(c.id)?'checked':''} ${c.isActive?'':'disabled'}>${esc(c.name)} · ${esc(c.platform)} (${esc(c.id)})</label>`).join('')}</fieldset><fieldset><legend>当前账号远端媒体</legend>${media.map(m=>`<label><input name="media" type="checkbox" value="${esc(m.id)}" ${item.remoteMediaIds.includes(m.id)?'checked':''}>${esc(m.id)} · ${esc(m.mimeType)}</label>`).join('')||'<p>尚无远端媒体</p>'}</fieldset><p>本地素材 ${esc(item.assetRefs.join(', ')||'无')}；本地路径不能冒充远端素材 ID。</p><a href="https://socialmedia.ydjia.com/media" target="_blank" rel="noopener">到发布账号上传素材</a> <button type="button" data-media-reload>刷新账号媒体</button><label>模式<select name="mode"><option value="immediate" ${item.plannedAt?'':'selected'}>立即</option><option value="scheduled" ${item.plannedAt?'selected':''}>排期</option></select></label><label>排期时间（ISO UTC，显示时区 ${esc(item.timezone)}）<input name="plannedAt" value="${esc(item.plannedAt||'')}" placeholder="2026-12-01T01:00:00Z"></label>${attempts.filter(a=>a.itemId===item.id&&a.mode==='scheduled'&&a.postId&&a.status!=='failed').map(a=>`<label><input name="ack" type="checkbox" value="${esc(a.id)}">确认旧排期 ${esc(a.id)} / ${esc(a.postId)} 仍在远端，本地编辑不会取消</label>`).join('')}<button type="button" data-save-selection>保存选择并送审</button><button type="button" data-review-version>批准当前版本</button><button type="submit">检查预算并准备确认</button><div role="alert"></div></form><div data-publish-confirm></div><div data-receipts>${attempts.filter(a=>a.itemId===item.id).map(publishReceipt).join('')}</div>`;
 const form=area.querySelector('form');const show=e=>form.querySelector('[role=alert]').textContent=e.message;
 const busy=async(button,fn)=>{if(button.disabled)return;button.disabled=true;try{await fn();}catch(e){show(e);}finally{if(button.isConnected)button.disabled=false;}};
 area.querySelector('[data-media-reload]').onclick=e=>busy(e.target,()=>openPublish(item));
 area.querySelector('[data-save-selection]').onclick=e=>busy(e.target,async()=>{const f=new FormData(form),plannedAt=f.get('mode')==='scheduled'?String(f.get('plannedAt')):null;await post('items/'+item.id,{expectedRevision:item.contentRevision,input:{title:item.title,channelIds:f.getAll('channels'),remoteMediaIds:f.getAll('media'),plannedAt}});item=items.find(x=>x.id===item.id);await openPublish(item);});
 area.querySelector('[data-review-version]').onclick=e=>busy(e.target,async()=>{await post('items/'+item.id+'/approve',{contentHash:item.contentHash});item=items.find(x=>x.id===item.id);await openPublish(item);});
 form.onsubmit=e=>{e.preventDefault();const button=form.querySelector('[type=submit]');busy(button,async()=>{const f=new FormData(form),ids=f.getAll('channels'),mediaIds=f.getAll('media'),mode=String(f.get('mode')),plannedAt=mode==='scheduled'?String(f.get('plannedAt')):null;if(JSON.stringify(ids)!==JSON.stringify(item.channelIds)||JSON.stringify(mediaIds)!==JSON.stringify(item.remoteMediaIds)||plannedAt!==item.plannedAt)throw Error('选择或时间已改变；请先保存并重新批准当前版本。');const reason=publishEligibility(item,cfg,channels,media);if(reason)throw Error(reason);const c=await post('items/'+item.id+'/prepare-publish',{input:{channelIds:ids,mode,plannedAt,acknowledgedAttemptIds:f.getAll('ack')}});const pane=area.querySelector('[data-publish-confirm]');pane.innerHTML=publishDialog(item,c);for(const el of form.elements)el.disabled=true;const consent=pane.querySelector('[data-consent]'),submit=pane.querySelector('[data-publish-submit]');consent.onchange=()=>submit.disabled=!consent.checked;pane.querySelector('[data-publish-close]').onclick=()=>openPublish(items.find(x=>x.id===item.id));submit.onclick=()=>{if(submit.disabled)return;submit.disabled=true;consent.disabled=true;(async()=>{try{await post('items/'+item.id+'/publish',{confirmationId:c.id});render();await openPublish(items.find(x=>x.id===item.id));}catch(e){pane.querySelector('[role=alert]').textContent=e.message+'；不自动重发，请关闭并读取回执核对。';}})();};});};
 wireRefresh(area,item);
}
function wireRefresh(area,item){for(const button of area.querySelectorAll('[data-publish-refresh]'))button.onclick=async()=>{if(button.disabled)return;button.disabled=true;try{const data=await api.request('/api/publisher/attempts/'+button.dataset.publishRefresh+'/refresh',{method:'POST',headers:{'x-workspace-token':token},body:JSON.stringify({revision})});revision=data.revision;onRevision(revision);items=data.items;attempts=data.attempts;await openPublish(items.find(x=>x.id===item.id));}catch(e){const alert=area.querySelector('[role=alert]');if(alert)alert.textContent=e.message;}finally{button.disabled=false;}};}
host.onchange=e=>{if(e.target.dataset.filter){filters[e.target.dataset.filter]=e.target.value;render();}if(e.target.hasAttribute('data-week')){week=e.target.value;render();}};
host.onclick=async e=>{const b=e.target.closest('[data-cp]');if(!b||b.disabled)return;const action=b.dataset.cp,x=items.find(x=>x.id===b.dataset.id);if(['approve','archive'].includes(action))b.disabled=true;try{if(action==='publish')await openPublish(x);if(action==='new')edit();if(action==='edit')edit(x);if(action==='cancel')render();if(action==='import')importForm();if(action==='list'||action==='week'){mode=action;render();}if(action==='approve'){await post('items/'+x.id+'/approve',{contentHash:x.contentHash});render();}if(action==='archive'){await post('items/'+x.id+'/archive',{expectedRevision:x.contentRevision});render();}if(action==='export'){const p=await api.request('/api/content/export'),url=URL.createObjectURL(new Blob([JSON.stringify(p,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='content-plan.json';a.click();URL.revokeObjectURL(url);}}catch(e){error(e);}finally{if(b.isConnected)b.disabled=false;}};
try{const history=await api.request('/api/publisher/attempts');attempts=history.attempts;const data=await api.request('/api/content/items');items=data.items;revision=data.revision;onRevision(revision);render();}catch(e){host.innerHTML='<div role="alert" class="error">'+esc(e.message)+'</div>';}}

export function publishEligibility(item,config,channels,media){
 if(!config.configured)return '发布服务未配置，请在服务器配置密钥。';
 if(!Number.isSafeInteger(config.maxCreditsPerPost)||config.maxCreditsPerPost<1||!Number.isSafeInteger(config.maxCreditsPerDay)||config.maxCreditsPerDay<1)return '请在设置明确填写正整数积分上限。';
 if(item.reviewStatus!=='approved'||item.approvedHash!==item.contentHash)return '当前版本尚未批准；保存渠道、素材及时间后重新批准。';
 if(!item.channelIds.length)return '请选择目标渠道。';
 if(item.channelIds.some(id=>!channels.some(c=>c.id===id&&c.isActive!==false)))return '目标渠道不可用，请刷新。';
 if(item.remoteMediaIds.some(id=>!media.some(m=>m.id===id)))return '远端素材不属于当前账号，请刷新并关联。';
 const selected=channels.filter(c=>item.channelIds.includes(c.id));
 if(selected.some(c=>['instagram','pinterest'].includes(c.platform.toLowerCase()))&&!item.remoteMediaIds.length)return '图片渠道需要实际远端素材 ID；本地图片尚未上传。';
 if(selected.some(c=>c.platform.toLowerCase()==='tiktok')&&!media.some(m=>item.remoteMediaIds.includes(m.id)&&m.mimeType.startsWith('video/')))return 'TikTok 需要实际远端视频素材。';
 return '';
}
export function publishDialog(item,c){return `<section data-confirmation="${esc(c.id)}"><h3>确认发布当前版本 ${esc(item.contentRevision)}</h3><pre>${esc(item.text)}</pre><p>版本摘要：${esc(c.contentHash)}<br>目标渠道：${esc(c.channelIds.join(', '))}<br>远端素材：${esc(item.remoteMediaIds.join(', ')||'无')}<br>模式：${esc(c.mode)}；时间：${esc(c.plannedAt||'立即')}<br>内容显示时区：${esc(item.timezone)}；积分日界线固定 Asia/Shanghai</p><p>当前余额 ${esc(c.balance)}；本次最高 ${esc(c.maxCredits)} 积分。有效至 ${esc(c.expiresAt)}。</p><p>服务未提供实际扣费明细，保守预留目标渠道数，不能把预留当作实际扣费。</p><label><input type="checkbox" data-consent>我确认上述正文、渠道、素材、时间与数值预算，授权本次提交</label><button type="button" data-publish-submit disabled>确认并提交</button><button type="button" data-publish-close>关闭</button><div role="alert"></div></section>`;}
export function publishReceipt(a){return `<article data-attempt="${esc(a.id)}"><h4>发布回执：${esc(a.status)}</h4>${a.approvedContent?`<h5>${esc(a.approvedContent.title)}</h5><pre>${esc(a.approvedContent.text)}</pre><p>已批准版本摘要 ${esc(a.contentHash)}；本地素材 ${esc(a.approvedContent.assetRefs.join(', ')||'无')}；远端素材 ${esc(a.approvedContent.remoteMediaIds.join(', ')||'无')}</p><details><summary>提交载荷与完整批准内容</summary><pre>${esc(JSON.stringify({approvedContent:a.approvedContent,submittedPayload:a.submittedPayload},null,2))}</pre></details>`:'<p>旧记录没有内容存档；历史标题、正文及素材不可恢复。</p>'}<p>批次 ${esc(a.id)}；远端帖子 ${esc(a.postId||'尚未确认')}<br>保守预留 ${esc(a.reservedCredits)}；实际积分 ${a.actualCredits===null?'尚未提供':esc(a.actualCredits)}</p>${a.channelIds?.map(id=>{const r=a.results.find(r=>r.channelId===id);return `<p>${esc(id)}：${esc(r?.status||'unknown')} ${r?.pending?'pending':''} ${esc(r?.error||'')}${r?.url&&/^https?:\/\//.test(r.url)?` <a href="${esc(r.url)}" target="_blank" rel="noopener">公开结果</a>`:''}</p>`;}).join('')||a.results.map(r=>`<p>${esc(r.channelId)}：${esc(r.status)} ${r.pending?'pending':''}</p>`).join('')}<p>${esc(a.error||'')} 排期或 unknown 不代表已发布；刷新只读取远端状态，不自动重发。编辑不会取消旧远端排期。</p>${a.postId?`<button data-publish-refresh="${esc(a.id)}">读取最新回执</button>`:`<p>远端帖子 ID 尚未知，刷新无法通过 get_post 查询本批次。请手动核对发布账号的帖子记录或工具日志；不要创建替代帖子，也不要把人工核对视为自动完成。</p><a data-publish-manual href="https://socialmedia.ydjia.com" target="_blank" rel="noopener">到发布账号手动核对记录</a>`}</article>`;}



export function receiptItemsForModule(items,tasks,moduleId){return moduleId==='content-operations'?items:moduleId==='social-media'?items.filter(item=>tasks.some(t=>t.id===item.sourceTaskId&&t.stage==='social-media')):[];}
export async function mountPublicationResults(host,{moduleId,tasks,token,onRevision}){let revision;async function load(){try{const [{items},data]=await Promise.all([api.request('/api/content/items'),api.request('/api/publisher/attempts')]);revision=data.revision;onRevision(revision);const scoped=receiptItemsForModule(items,tasks,moduleId),ids=new Set(scoped.map(x=>x.id));host.innerHTML='<div role="alert"></div>'+data.attempts.filter(a=>ids.has(a.itemId)).map(a=>publishReceipt(a)).join('');if(!data.attempts.some(a=>ids.has(a.itemId)))host.innerHTML='<p>暂无本项目实际发布回执。</p>';for(const b of host.querySelectorAll('[data-publish-refresh]'))b.onclick=async()=>{if(b.disabled)return;b.disabled=true;try{const d=await api.request('/api/publisher/attempts/'+b.dataset.publishRefresh+'/refresh',{method:'POST',headers:{'x-workspace-token':token},body:JSON.stringify({revision})});onRevision(d.revision);await load();}catch(e){host.querySelector('[role=alert]').textContent=e.message;}finally{b.disabled=false;}};}catch(e){host.innerHTML='<p role="alert">'+esc(e.message)+'</p>';}}await load();}

export async function readPublicationState(request=api.request){const history=await request('/api/publisher/attempts');const content=await request('/api/content/items');return {items:content.items,attempts:history.attempts,revision:content.revision};}
