import {MODULES,moduleForStage} from '../modules.js';
import {safeWebUrl} from '../safe-url.js';
function webLink(value,label,esc){let url;try{url=new URL(String(value));}catch{return esc(label??value);}return safeWebUrl(url.href)?`<a href="${esc(url.href)}" target="_blank" rel="noopener noreferrer">${esc(label??value)}</a>`:esc(label??value);}
function phoneLink(value,esc){const phone=String(value??'').trim();return /^\+?[0-9][0-9 ()-]{5,24}$/.test(phone)?`<a href="tel:${esc(phone.replace(/[ ()-]/g,''))}">${esc(phone)}</a>`:esc(phone);}
export function expertDetail(e,esc){return `<p>${esc(e.name)}</p><p>${esc(e.description)}</p><p>付费服务；具体范围与费用联系确认。免费技能持续可用。</p><p>联系电话（微信同号）：${phoneLink(e.contact,esc)}</p>${(e.websites||[]).map(url=>`<p>${webLink(url,null,esc)}</p>`).join('')}${(e.projectLinks||[]).map(link=>`<p>${webLink(link.url,link.title,esc)}</p>`).join('')}<p>联系入口不包含客户资料。专家没有客户目录读取权限。由客户主动选择成果并手动导出后，自行决定是否分享。</p>`;}
export function servicesView({state,heading,button,esc}){const c=state.serviceCatalog||{experts:[],templates:[]};return heading('专家与陪跑','按需联系；计划进度来自实际成果的客户验收。')+c.experts.map(e=>`<section class="panel">${expertDetail(e,esc)}${button('复制联系电话','expert-copy',e.id)}</section>`).join('')+c.templates.map(t=>`<section class="panel"><h2>${esc(t.title)}</h2><p>本地交付计划模板；创建不代表已购买服务或专家开始执行。</p><p>${esc(t.goals.join('；'))}</p>${button('创建交付计划','delivery-create',t.id,true)}</section>`).join('')+(state.deliveryPrograms||[]).map(p=>`<section class="panel"><h2>${esc(p.title)}</h2><p>客户验收进度：${p.progress.completed} / ${p.progress.total}</p>${p.taskIds.map(id=>{const t=state.tasks.find(t=>t.id===id);return t?`<p>${esc(t.name)} · ${esc(t.status)} ${button('查看任务','task',id)}</p>`:'';}).join('')}<p>成果：${p.artifactIds.length}；当前有效验收：${p.progress.reviewIds.length}</p>${button('选择成果并手动导出','delivery-share',p.id)}</section>`).join('');}

export const CONSULTATION_EXPERT={"id":"cola","name":"搞跨境的可乐哥","modules":["site-and-content","seo-geo","content-operations","acquisition","next-cycle","social-media","facebook-ads","google-ads","email-outreach"],"contact":"13631179943","description":"AI建站、WordPress、SEO、Google Ads、Facebook广告、数据分析","websites":["https://www.ydjia.com"],"projectLinks":[],"qrImage":null};
export function consultationForModule(moduleId){const module=MODULES.find(m=>m.id===(moduleForStage(moduleId)||moduleId));return module&&!module.free?{...CONSULTATION_EXPERT,modules:[...CONSULTATION_EXPERT.modules],websites:[...CONSULTATION_EXPERT.websites]}:null;}
export function moduleConsultationView(moduleId,esc){const e=consultationForModule(moduleId);return e?`<section class="panel module-consultation"><h2>专家咨询联系</h2>${expertDetail(e,esc)}<div class="qr-placeholder" role="img" aria-label="微信二维码图片待提供">微信二维码图片待提供</div><p>未提供真实图片前显示占位。</p><button class="btn" data-action="expert-detail" data-id="cola">查看专家与联系</button></section>`:'';}

// Legacy configured service rendering remains available to delivery consumers.
export function moduleServices({state,moduleId,button,esc}){const rows=(state.serviceCatalog?.services||[]).filter(s=>s.modules.includes(moduleId));return rows.map(s=>{const e=state.serviceCatalog.experts.find(e=>e.id===s.expertId&&e.contact&&e.modules.includes(moduleId));return e?`<div><p>相关专家：${esc(e.name)} · 付费服务（范围与费用联系确认）</p><p>${esc(s.scope)}</p>${button('查看专家与联系','expert-detail',e.id)}</div>`:'';}).join('')||'<p>相关专家：尚未配置经确认的信息；免费技能持续可用。</p>';}
