import {backupView} from './backup.js';
/* 知识库同步自检状态（2026-10-08 定制）：比对线上文件与 .sync-manifest.json 基线，
   用于发现「本地改了但忘了同步到发布目录」或「线上被改坏」。 */
function kbStatusHtml(state){const k=(state&&state.kbCheck)||{};
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 if(k.status==='ok')return '<span class="pill">一致</span> 线上 '+k.present+' 份知识文件与基线一致'+(k.at?'（同步于 '+esc(String(k.at).slice(0,19).replace('T',' '))+'）':'');
 if(k.status==='drift')return '<span class="pill">不一致</span> '+k.drifted.length+' 份与基线不符：'+esc(k.drifted.join('、'))+'。本地运行 node scripts/sync-knowledge.mjs 同步后重新发布';
 if(k.status==='no-baseline')return '<span class="pill">无基线</span> 未找到 .sync-manifest.json，运行 node scripts/sync-knowledge.mjs 生成';
 return '<span class="pill">未知</span> 尚未校验';}
export function settingsView({state,updateInfo,heading,button,esc}){return heading('项目与设置','使用当前客户项目文件，保留 WorkBuddy 原生执行入口。')+`<section class="panel"><h2>项目头像</h2><img src="${esc(state.settings?.avatar||'brand.jpg')}" alt="当前头像" style="width:72px;height:72px;object-fit:cover;border-radius:16px"><p><label>上传头像（PNG/JPEG/WebP，最大256KB）<input id="avatar-file" type="file" accept="image/png,image/jpeg,image/webp"></label></p>${button('恢复默认头像','avatar-reset')}<p class="note">保存在客户本地项目，不上传到版本检查服务。</p></section><section class="panel"><h2>版本与更新</h2><p>当前版本：${esc(state.version)}</p><p>${updateInfo?updateInfo.error?esc(updateInfo.error):updateInfo.available?'发现新版本：'+esc(updateInfo.latest):'已检查发布版本：'+esc(updateInfo.latest)+'，无需更新':'尚未检查'}</p>${button('检查新版本','check-update')}${button('检查本地更新保护','update-inspect')}${updateInfo?.available?button('WorkBuddy 更新部署指令','update-guide','',true):''}<p class="note">在 WorkBuddy 更新；先备份并合并本地定制，冲突不强制覆盖。${esc(updateInfo?.notes||'')}</p></section>`+`<section class="panel"><h2>功能技能</h2>${button('安装项目技能','install-skills','',true)}<p class="note">安装到当前项目 .codebuddy/skills/，同名不同内容不覆盖。文件安装不等于宿主已加载。</p>${Object.values(state.skills).map(x=>`<div class="row"><span>${esc(x.title)}</span><span class="pill">${x.status==='installed'?'项目文件已安装':x.status==='different'?'客户版本不同':'待安装'}</span></div>`).join('')}<h2>实际文件目录</h2><div class="knowledge">${esc(state.projectRoot)}\ngrowth-workspace/</div><p class="note">启动时用 --root 选择客户项目；不同客户使用独立目录。</p><h2>知识库同步状态</h2><p>${kbStatusHtml(state)}</p><p class="note">线上知识库来自发布目录 wb-public/growth-workspace/knowledge/。本地源文件改完后必须运行 <b>node scripts/sync-knowledge.mjs</b> 同步，再发布；本状态用于发现漏同步或线上被改坏。<b>--check</b> 只检查不改动，有差异时退出码 1。</p><h2>WorkBuddy 项目 / 空间</h2><p>项目：${esc(state.profile.projectRef||'未填写')}<br>空间：${esc(state.profile.spaceRef||'未填写')}<br>关联状态：待宿主验证</p>${button('填写关联资料','profile')}<p class="note">在 WorkBuddy 项目中启用 yundian-growth-workbench 技能，上传知识文件到项目资料库。平台当前不自动创建云端空间，不保存供应商密钥。广告仅只读分析。</p></section>`+backupView({button,esc});}
