import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('..',import.meta.url));
const arg=process.argv.indexOf('--output');const output=path.resolve(arg<0?path.join(root,'dist/skills-working-tree'):process.argv[arg+1]);
const registry=JSON.parse(fs.readFileSync(path.join(root,'skills/registry.json'),'utf8'));
const release=JSON.parse(fs.readFileSync(path.join(root,'package.json'),'utf8')).version;
const sha=buffer=>crypto.createHash('sha256').update(buffer).digest('hex');
const table=Array.from({length:256},(_,n)=>{let c=n;for(let k=0;k<8;k++)c=c&1?0xedb88320^(c>>>1):c>>>1;return c>>>0;});
const crc=body=>{let c=0xffffffff;for(const b of body)c=table[(c^b)&255]^(c>>>8);return (c^0xffffffff)>>>0;};
function zip(files){const chunks=[],central=[];let offset=0;for(const {name,body} of files){if(name.startsWith('/')||name.split('/').includes('..')||name.includes('\\'))throw Error('Unsafe archive entry');const n=Buffer.from(name),h=Buffer.alloc(30);h.writeUInt32LE(0x04034b50);h.writeUInt16LE(20,4);h.writeUInt16LE(0x800,6);h.writeUInt16LE(33,12);h.writeUInt32LE(crc(body),14);h.writeUInt32LE(body.length,18);h.writeUInt32LE(body.length,22);h.writeUInt16LE(n.length,26);chunks.push(h,n,body);const c=Buffer.alloc(46);c.writeUInt32LE(0x02014b50);c.writeUInt16LE(20,4);c.writeUInt16LE(20,6);c.writeUInt16LE(0x800,8);c.writeUInt16LE(33,14);c.writeUInt32LE(crc(body),16);c.writeUInt32LE(body.length,20);c.writeUInt32LE(body.length,24);c.writeUInt16LE(n.length,28);c.writeUInt32LE(offset,42);central.push(c,n);offset+=h.length+n.length+body.length;}const directory=Buffer.concat(central),end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50);end.writeUInt16LE(files.length,8);end.writeUInt16LE(files.length,10);end.writeUInt32LE(directory.length,12);end.writeUInt32LE(offset,16);return Buffer.concat([...chunks,directory,end]);}
function walk(dir,prefix){const files=[];for(const ent of fs.readdirSync(dir,{withFileTypes:true}).sort((a,b)=>a.name.localeCompare(b.name))){if(ent.name==='__pycache__'||ent.name.endsWith('.pyc'))continue;const file=path.join(dir,ent.name);if(ent.isSymbolicLink())throw Error('Skill symlinks are not packaged');if(ent.isDirectory())files.push(...walk(file,prefix+'/'+ent.name));else if(ent.isFile())files.push({name:prefix+'/'+ent.name,body:fs.readFileSync(file)});}return files;}
const aliases=Object.fromEntries(Object.entries(registry).map(([stage,v])=>[stage,v.id]));
const manifest={formatVersion:1,releaseVersion:release,buildLabel:'working-tree',published:false,aliases,installPolicy:'Preserve every differing customer file. Compare per-file SHA-256; install to a separate official version directory and explicitly select the new official skill after reviewing differences. Do not overwrite custom skills or registry.',skills:[],packages:[]};
const all=[];fs.mkdirSync(output,{recursive:true});
for(const ent of fs.readdirSync(path.join(root,'skills'),{withFileTypes:true}).sort((a,b)=>a.name.localeCompare(b.name))){if(!ent.isDirectory()||!fs.existsSync(path.join(root,'skills',ent.name,'SKILL.md')))continue;const files=walk(path.join(root,'skills',ent.name),ent.name),entry=Object.values(registry).find(v=>v.id===ent.name);const skill={skillId:ent.name,version:entry?.version||release,buildLabel:'working-tree',files:files.map(f=>({path:f.name,sha256:sha(f.body),size:f.body.length}))};manifest.skills.push(skill);const local={...skill,releaseVersion:release,published:false,installPolicy:manifest.installPolicy};files.push({name:ent.name+'/manifest.json',body:Buffer.from(JSON.stringify(local,null,2)+'\n')});const file=ent.name+'-v'+skill.version+'-working-tree.zip',body=zip(files);fs.writeFileSync(path.join(output,file),body);manifest.packages.push({file,skillId:ent.name,sha256:sha(body),size:body.length});all.push(...files);}
all.push({name:'registry.json',body:fs.readFileSync(path.join(root,'skills/registry.json'))},{name:'manifest.json',body:Buffer.from(JSON.stringify(manifest,null,2)+'\n')});const file='yundian-growth-skills-v'+release+'-working-tree.zip',body=zip(all);fs.writeFileSync(path.join(output,file),body);manifest.packages.push({file,skillId:null,sha256:sha(body),size:body.length});fs.writeFileSync(path.join(output,'manifest.json'),JSON.stringify(manifest,null,2)+'\n');console.log(JSON.stringify({output,skills:manifest.skills.length,packages:manifest.packages.length,files:manifest.packages.map(p=>path.join(output,p.file))},null,2));
